# Generated by Django 4.2.30 on 2026-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0004_posterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='เลขที่ใบ เช่น 1, 2, 3 ...')),
                ('image', models.ImageField(upload_to='happy_workplace/fortunes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
