# Generated by Django 4.2.30 on 2026-09-20 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0006_wordlescore_wordlesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortuneslip',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='เลขที่ใบ 1-28', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
