# Generated by Django 4.2.30 on 2026-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0008_maplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('score', models.PositiveIntegerField()),
                ('detail', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MapLocation',
        ),
    ]
