# Generated by Django 5.2.16 on 2026-09-21 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0009_gamescore_delete_maplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.CreateModel(
            name='SquaresWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=12, unique=True)),
                ('meaning', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('H', 'แอร์และทำความเย็น'), ('E', 'ไฟฟ้าและควบคุม'), ('M', 'เครื่องกลและวัสดุ'), ('S', 'ความปลอดภัยและมาตรฐาน'), ('G', 'ทั่วไปและองค์กร')], default='G', max_length=1)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
