# Generated by Django 5.2.16 on 2026-09-21 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0011_seed_squares_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyWorkplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_play_limit', models.PositiveSmallIntegerField(default=3, help_text='จำนวนครั้งที่เล่นได้ต่อเกมต่อวัน (0 = ไม่จำกัด)', validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('day', models.DateField(db_index=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'client_id', 'day'), name='uniq_gameplay_per_day')],
            },
        ),
    ]
