# Generated by Django 5.2.16 on 2026-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0014_replace_squares_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresword',
            name='category',
            field=models.CharField(choices=[('W', 'การทำงานและสำนักงาน'), ('F', 'อาหารและเครื่องดื่ม'), ('T', 'การเดินทางและการท่องเที่ยว'), ('H', 'สุขภาพและการแพทย์'), ('E', 'อารมณ์และความรู้สึก')], default='W', max_length=1),
        ),
    ]
