# Generated by Django 5.2.16 on 2026-09-23 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0016_typingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='happyworkplacesettings',
            name='dream_play_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='happyworkplacesettings',
            name='fortune_play_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='happyworkplacesettings',
            name='phone_analysis_play_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
