# Generated by Django 5.2.16 on 2026-09-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_workplace', '0017_happyworkplacesettings_dream_play_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresword',
            name='category',
            field=models.CharField(choices=[('W', 'การทำงานและสำนักงาน'), ('F', 'อาหารและเครื่องดื่ม'), ('T', 'การเดินทางและการท่องเที่ยว'), ('H', 'สุขภาพและการแพทย์'), ('E', 'อารมณ์และความรู้สึก'), ('C', 'เครื่องแต่งกายและเครื่องประดับ')], default='W', max_length=1),
        ),
    ]
