# Generated by Django 5.2.16 on 2026-09-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=30, unique=True, verbose_name='Part Number')),
                ('desc', models.CharField(max_length=200, verbose_name='Description (EN)')),
                ('descth', models.CharField(blank=True, max_length=200, verbose_name='รายละเอียดเพิ่มเติม')),
                ('cat', models.CharField(blank=True, max_length=30, verbose_name='Category')),
                ('sub', models.CharField(blank=True, max_length=50, verbose_name='Sub-Category')),
                ('mfr', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='Model / Spec')),
                ('unit', models.CharField(default='EA', max_length=10, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Price (THB)')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='Min Stock')),
                ('cur_stock', models.PositiveIntegerField(default=0, verbose_name='Current Stock')),
                ('max_stock', models.PositiveIntegerField(default=0, verbose_name='Max Stock')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('lead_time_days', models.CharField(blank=True, max_length=20, verbose_name='Lead Time (วัน)')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pn'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('tx_type', models.CharField(choices=[('receive', 'รับเข้า'), ('withdraw', 'เบิกออก'), ('update', 'แก้ไข'), ('replace', 'เปลี่ยนทดแทน'), ('new', 'เพิ่มใหม่')], max_length=10)),
                ('delta', models.IntegerField(default=0)),
                ('before', models.IntegerField(default=0)),
                ('after', models.IntegerField(default=0)),
                ('by', models.CharField(blank=True, max_length=100, verbose_name='ผู้ดำเนินการ')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ / เหตุผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_label', models.CharField(blank=True, help_text='ใช้เฉพาะรายการที่ import มาจากประวัติเดิม ซึ่งไม่มี timestamp จริง', max_length=40, verbose_name='วันที่ (สำหรับข้อมูลนำเข้า)')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='spare_parts.sparepart')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
