# Generated by Django 5.2.16 on 2026-09-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_seed_spare_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['pn']},
        ),
    ]
