# Generated by Django 5.2.16 on 2026-09-22 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Production, Employee, Test Room', max_length=100, unique=True)),
                ('server', models.CharField(help_text='Host or host\\instance, e.g. 192.168.1.100', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, help_text='Leave blank for the driver default (1433)', null=True)),
                ('database_name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('encrypted_password', models.TextField(blank=True)),
                ('driver', models.CharField(default='ODBC Driver 18 for SQL Server', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive connections are hidden from Data Explorer')),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
