# Generated by Django 5.2.16 on 2026-09-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสพนักงาน')),
                ('history_no', models.CharField(max_length=30, unique=True, verbose_name='เลขที่ประวัติ')),
                ('name_th', models.CharField(max_length=150, verbose_name='ชื่อภาษาไทย')),
                ('name_en', models.CharField(max_length=150, verbose_name='ชื่อภาษาอังกฤษ')),
                ('working_group', models.CharField(blank=True, max_length=50, verbose_name='กลุ่มงาน')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='ตำแหน่งงาน')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='วุฒิการศึกษา')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มงาน')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วันที่เกิด')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='training_history/employees/', verbose_name='รูปถ่ายพนักงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['emp_id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300, verbose_name='หลักสูตรที่อบรม')),
                ('training_date', models.CharField(max_length=60, verbose_name='วันที่อบรม')),
                ('trainer', models.CharField(max_length=200, verbose_name='ผู้ฝึกอบรม / สถาบัน')),
                ('evidence_label', models.CharField(default='Certificate', max_length=100, verbose_name='หลักฐานผ่านการอบรม')),
                ('recorder', models.CharField(blank=True, max_length=100, verbose_name='ผู้บันทึก')),
                ('record_date', models.CharField(blank=True, max_length=60, verbose_name='วันที่บันทึก')),
                ('ref_id', models.CharField(blank=True, max_length=50, verbose_name='อ้างอิงเอกสาร/รูป')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='training_history/evidence/', verbose_name='ไฟล์หลักฐาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_history.trainingemployee')),
            ],
            options={
                'ordering': ['employee__emp_id', 'id'],
            },
        ),
    ]
