"""Starter word bank for the Squares game.

Each line: WORD|category|Thai meaning. Words are A-Z only, 3-10 letters,
general everyday vocabulary (not specialized/technical terms).
Categories: W = work & office, F = food & dining, T = travel & commute,
H = health & medical, E = emotions & feelings, C = clothing & accessories.
Admins can add, edit and delete words from the Happy Workplace manage page.
"""

_RAW = """
OFFICE|W|สำนักงาน
DESK|W|โต๊ะทำงาน
CHAIR|W|เก้าอี้
TABLE|W|โต๊ะ
MEETING|W|การประชุม
MANAGER|W|ผู้จัดการ
EMAIL|W|อีเมล
REPORT|W|รายงาน
PROJECT|W|โครงการ
DEADLINE|W|กำหนดส่งงาน
TEAM|W|ทีมงาน
BOSS|W|หัวหน้า
STAFF|W|พนักงาน
SALARY|W|เงินเดือน
WAGE|W|ค่าจ้าง
INTERVIEW|W|การสัมภาษณ์
RESUME|W|ประวัติย่อ
CONTRACT|W|สัญญา
CLIENT|W|ลูกค้า
CUSTOMER|W|ลูกค้า
INVOICE|W|ใบแจ้งหนี้
BUDGET|W|งบประมาณ
PRINTER|W|เครื่องพิมพ์
COMPUTER|W|คอมพิวเตอร์
LAPTOP|W|โน้ตบุ๊ก
KEYBOARD|W|แป้นพิมพ์
MOUSE|W|เมาส์
MONITOR|W|จอภาพ
SCREEN|W|หน้าจอ
PHONE|W|โทรศัพท์
CALL|W|การโทร
SCHEDULE|W|ตารางเวลา
CALENDAR|W|ปฏิทิน
TASK|W|งานที่ต้องทำ
GOAL|W|เป้าหมาย
PLAN|W|แผนงาน
STRATEGY|W|กลยุทธ์
SLIDE|W|สไลด์นำเสนอ
DOCUMENT|W|เอกสาร
FILE|W|ไฟล์
FOLDER|W|แฟ้มเอกสาร
PAPER|W|กระดาษ
PEN|W|ปากกา
PENCIL|W|ดินสอ
STAPLER|W|เครื่องเย็บกระดาษ
CLIP|W|คลิปหนีบกระดาษ
NOTE|W|บันทึกย่อ
MEMO|W|บันทึกข้อความ
AGENDA|W|วาระการประชุม
MINUTES|W|รายงานการประชุม
VOTE|W|การลงคะแนน
DECISION|W|การตัดสินใจ
POLICY|W|นโยบาย
RULE|W|กฎ ระเบียบ
TRAINING|W|การฝึกอบรม
WORKSHOP|W|การอบรมเชิงปฏิบัติ
SEMINAR|W|การสัมมนา
COLLEAGUE|W|เพื่อนร่วมงาน
INTERN|W|นักศึกษาฝึกงาน
TRAINEE|W|ผู้ฝึกงาน
SUPERVISOR|W|หัวหน้างาน
DIRECTOR|W|ผู้อำนวยการ
EXECUTIVE|W|ผู้บริหาร
PAYROLL|W|บัญชีเงินเดือน
BONUS|W|โบนัส
PROMOTION|W|การเลื่อนตำแหน่ง
RAISE|W|การขึ้นเงินเดือน
VACATION|W|วันหยุดพักร้อน
LEAVE|W|การลางาน
SHIFT|W|กะทำงาน
BREAK|W|เวลาพัก
LUNCH|W|อาหารกลางวัน
LOBBY|W|ล็อบบี้
RECEPTION|W|แผนกต้อนรับ
ELEVATOR|W|ลิฟต์
STAIRS|W|บันได
PARKING|W|ที่จอดรถ
BADGE|W|บัตรพนักงาน
SECURITY|W|ฝ่ายรักษาความปลอดภัย
WIFI|W|ไวไฟ
INTERNET|W|อินเทอร์เน็ต
NETWORK|W|เครือข่าย
SERVER|W|เซิร์ฟเวอร์
SOFTWARE|W|ซอฟต์แวร์
HARDWARE|W|ฮาร์ดแวร์
SYSTEM|W|ระบบ
UPDATE|W|การอัปเดต
BACKUP|W|การสำรองข้อมูล
PASSWORD|W|รหัสผ่าน
LOGIN|W|การเข้าสู่ระบบ
ACCOUNT|W|บัญชีผู้ใช้
PROFILE|W|ข้อมูลส่วนตัว
SIGNATURE|W|ลายเซ็น
STAMP|W|ตราประทับ
LETTER|W|จดหมาย
ENVELOPE|W|ซองจดหมาย
COURIER|W|บริการส่งพัสดุ
DELIVERY|W|การจัดส่ง
SHIPMENT|W|การขนส่งสินค้า
WAREHOUSE|W|คลังสินค้า
INVENTORY|W|สินค้าคงคลัง
STOCK|W|สต๊อกสินค้า
SUPPLY|W|เสบียง วัสดุ
VENDOR|W|ผู้ขายสินค้า
SUPPLIER|W|ผู้จัดหาสินค้า
PARTNER|W|หุ้นส่วน
STARTUP|W|ธุรกิจเริ่มต้น
COMPANY|W|บริษัท
FIRM|W|บริษัท ห้าง
INDUSTRY|W|อุตสาหกรรม
MARKET|W|ตลาด
SALES|W|ฝ่ายขาย
MARKETING|W|การตลาด
BRAND|W|แบรนด์
LOGO|W|ตราสัญลักษณ์
WEBSITE|W|เว็บไซต์
ONLINE|W|ออนไลน์
DIGITAL|W|ดิจิทัล
DATA|W|ข้อมูล
ANALYSIS|W|การวิเคราะห์
RESEARCH|W|การวิจัย
SURVEY|W|แบบสำรวจ
FEEDBACK|W|ข้อเสนอแนะ
REVIEW|W|การประเมิน
AUDIT|W|การตรวจสอบบัญชี
FINANCE|W|การเงิน
TAX|W|ภาษี
PROFIT|W|กำไร
LOSS|W|ขาดทุน
REVENUE|W|รายได้
EXPENSE|W|ค่าใช้จ่าย
COST|W|ต้นทุน
PRICE|W|ราคา
DISCOUNT|W|ส่วนลด
OFFER|W|ข้อเสนอ
DEAL|W|ข้อตกลง
AGREEMENT|W|ข้อตกลง สัญญา
APPROVE|W|การอนุมัติ
REJECT|W|การปฏิเสธ
CANCEL|W|การยกเลิก
CONFIRM|W|การยืนยัน
REMINDER|W|การเตือนความจำ
NOTICE|W|ประกาศ
VERSION|W|เวอร์ชัน
DRAFT|W|ฉบับร่าง
EDIT|W|การแก้ไข
SUBMIT|W|การส่งงาน
UPLOAD|W|การอัปโหลด
DOWNLOAD|W|การดาวน์โหลด
ATTACH|W|การแนบไฟล์
FORWARD|W|การส่งต่อ
REPLY|W|การตอบกลับ
INBOX|W|กล่องข้อความเข้า
DELETE|W|การลบ
ARCHIVE|W|การเก็บถาวร
PRINT|W|การพิมพ์
SCAN|W|การสแกน
COPY|W|สำเนา
PASTE|W|การวาง
FONT|W|แบบอักษร
FORMAT|W|รูปแบบ
TEMPLATE|W|แม่แบบ
LAYOUT|W|การจัดวาง
DESIGN|W|การออกแบบ
GRAPHIC|W|กราฟิก
CHART|W|แผนภูมิ
GRAPH|W|กราฟ
FORMULA|W|สูตรคำนวณ
PROJECTOR|W|เครื่องฉายภาพ
MARKER|W|ปากกาเมจิก
BINDER|W|แฟ้มเข้าเล่ม
CABINET|W|ตู้เอกสาร
DRAWER|W|ลิ้นชัก
SHELF|W|ชั้นวางของ
STORAGE|W|พื้นที่จัดเก็บ
LABEL|W|ป้ายชื่อ
TAG|W|ป้ายกำกับ
RECEIPT|W|ใบเสร็จ
VOUCHER|W|บัตรกำนัล
COUPON|W|คูปอง
WARRANTY|W|การรับประกัน
REFUND|W|การคืนเงิน
COMPLAINT|W|ข้อร้องเรียน
CLAIM|W|การเรียกร้อง
INSURANCE|W|ประกันภัย
PENSION|W|เงินบำนาญ
BENEFIT|W|สวัสดิการ
OVERTIME|W|การทำงานล่วงเวลา
ABSENT|W|การขาดงาน
ATTENDANCE|W|การเข้างาน
UNIFORM|W|เครื่องแบบ
HANDBOOK|W|คู่มือพนักงาน
MANUAL|W|คู่มือการใช้งาน
PROCEDURE|W|ขั้นตอนปฏิบัติ
PROCESS|W|กระบวนการ
WORKFLOW|W|ขั้นตอนการทำงาน
MILESTONE|W|จุดหมายสำคัญ
TARGET|W|เป้าหมาย
QUOTA|W|เป้ายอดขาย
SKILL|W|ทักษะ
TALENT|W|พรสวรรค์
EXPERTISE|W|ความเชี่ยวชาญ
DIPLOMA|W|ประกาศนียบัตร
DEGREE|W|ปริญญา
LICENSE|W|ใบอนุญาต
PERMIT|W|ใบอนุญาต
VISA|T|วีซ่า
PASSPORT|T|หนังสือเดินทาง
FORM|W|แบบฟอร์ม
CHECKLIST|W|รายการตรวจสอบ
SUMMARY|W|บทสรุป
OUTLINE|W|โครงร่าง
PROPOSAL|W|ข้อเสนอโครงการ
PITCH|W|การนำเสนอโครงการ
IDEA|W|ความคิด
CONCEPT|W|แนวคิด
SOLUTION|W|ทางแก้ปัญหา
PROBLEM|W|ปัญหา
ISSUE|W|ประเด็นปัญหา
CHALLENGE|W|ความท้าทาย
OBSTACLE|W|อุปสรรค
RISK|W|ความเสี่ยง
PRIORITY|W|ลำดับความสำคัญ
URGENT|W|ด่วนมาก
ROUTINE|W|งานประจำวัน
DAILY|W|รายวัน
WEEKLY|W|รายสัปดาห์
MONTHLY|W|รายเดือน
ANNUAL|W|รายปี
LEDGER|W|สมุดบัญชี
JOURNAL|W|สมุดบันทึกบัญชี
BALANCE|W|ยอดคงเหลือ
ASSET|W|สินทรัพย์
EQUITY|W|หุ้นส่วนกิจการ
CAPITAL|W|เงินทุน
INVESTMENT|W|การลงทุน
CHAIRMAN|W|ประธาน
FOUNDER|W|ผู้ก่อตั้ง
ALLIANCE|W|พันธมิตร
BRANCH|W|สาขา
DEPARTMENT|W|แผนก
SECTION|W|ส่วนงาน
UNIT|W|หน่วยงาน
ROLE|W|บทบาท
TITLE|W|ตำแหน่ง
POSITION|W|ตำแหน่งงาน
RANK|W|ยศ ระดับ
DELEGATE|W|การมอบหมายงาน
ASSIGN|W|การมอบหมาย
ALLOCATE|W|การจัดสรร
ORGANIZE|W|การจัดระเบียบ
COORDINATE|W|การประสานงาน
NEGOTIATE|W|การเจรจาต่อรอง
RESOLVE|W|การแก้ไขปัญหา
SETTLE|W|การยุติข้อพิพาท
LAUNCH|W|การเปิดตัวสินค้า
RELEASE|W|การเผยแพร่
PUBLISH|W|การตีพิมพ์
PROMOTE|W|การส่งเสริม
CAMPAIGN|W|แคมเปญ
EVENT|W|กิจกรรม
EXHIBITION|W|งานนิทรรศการ
BOOTH|W|บูธ
BANNER|W|แบนเนอร์
POSTER|W|โปสเตอร์
FLYER|W|ใบปลิว
BROCHURE|W|โบรชัวร์
CATALOG|W|แคตตาล็อก
SAMPLE|W|ตัวอย่างสินค้า
PROTOTYPE|W|ต้นแบบ
MODEL|W|แบบจำลอง
SKETCH|W|ภาพร่าง
EDITION|W|ฉบับพิมพ์
CHAPTER|W|บท
PARAGRAPH|W|ย่อหน้า
SENTENCE|W|ประโยค
CLAUSE|W|ข้อสัญญา
TERM|W|เงื่อนไข
CONDITION|W|เงื่อนไข
STANDARD|W|มาตรฐาน
CRITERIA|W|เกณฑ์
INDICATOR|W|ตัวชี้วัด
STATISTIC|W|สถิติ
AVERAGE|W|ค่าเฉลี่ย
TOTAL|W|ยอดรวม
REMAINDER|W|ยอดคงเหลือ
DEPOSIT|W|เงินมัดจำ
WITHDRAWAL|W|การถอนเงิน
TRANSFER|W|การโอนเงิน
PAYMENT|W|การชำระเงิน
LOAN|W|เงินกู้
CREDIT|W|เครดิต
DEBIT|W|เดบิต
CASH|W|เงินสด
CURRENCY|W|สกุลเงิน
INTEREST|W|ดอกเบี้ย
DIVIDEND|W|เงินปันผล
SHARE|W|หุ้น
FUND|W|กองทุน
BROKER|W|นายหน้า
AGENT|W|ตัวแทน
DEALER|W|ตัวแทนจำหน่าย
RETAILER|W|ผู้ค้าปลีก
FRANCHISE|W|แฟรนไชส์
TRADEMARK|W|เครื่องหมายการค้า
PATENT|W|สิทธิบัตร
COPYRIGHT|W|ลิขสิทธิ์
LEGAL|W|ทางกฎหมาย
LAWYER|W|ทนายความ
ATTORNEY|W|ทนายความ
WITNESS|W|พยาน
EVIDENCE|W|หลักฐาน
COURT|W|ศาล
LAWSUIT|W|คดีความ
COMPLIANCE|W|การปฏิบัติตามกฎ
REGULATION|W|กฎระเบียบ
AMENDMENT|W|การแก้ไขเพิ่มเติม
APPENDIX|W|ภาคผนวก
REFERENCE|W|เอกสารอ้างอิง
CITATION|W|การอ้างอิง
GLOSSARY|W|อภิธานศัพท์
INDEX|W|ดัชนี
JOB|W|งาน
CAREER|W|อาชีพ
SKILLED|W|มีทักษะ
EXPERT|W|ผู้เชี่ยวชาญ
NOVICE|W|มือใหม่
MENTOR|W|พี่เลี้ยง
COACH|W|โค้ช
LEADER|W|ผู้นำ
FOLLOWER|W|ผู้ตาม
VOLUNTEER|W|อาสาสมัคร
FREELANCE|W|งานอิสระ
REMOTE|W|ทำงานทางไกล
HYBRID|W|รูปแบบผสมผสาน
COMMUTE|W|การเดินทางไปทำงาน
PUNCTUAL|W|ตรงต่อเวลา
EFFICIENT|W|มีประสิทธิภาพ
PRODUCTIVE|W|มีผลิตผล
QUALITY|W|คุณภาพ
QUANTITY|W|ปริมาณ
OUTPUT|W|ผลผลิต
INPUT|W|ปัจจัยนำเข้า
RESOURCE|W|ทรัพยากร
BUDGETING|W|การจัดทำงบประมาณ
FORECAST|W|การคาดการณ์
BRIEF|W|การบรรยายสรุป
DEBRIEF|W|การสรุปหลังงาน
HUDDLE|W|การรวมทีมพูดคุยสั้นๆ
SYNC|W|การประชุมย่อย
CHECKIN|W|การเช็กอินงาน
STATUS|W|สถานะงาน
PROGRESS|W|ความคืบหน้า
BLOCKER|W|อุปสรรคงาน
ESCALATE|W|การยกระดับปัญหา
FOLLOWUP|W|การติดตามงาน
PENDING|W|รอดำเนินการ
OVERDUE|W|เลยกำหนด
ONSITE|W|ทำงานที่ไซต์งาน
OFFSITE|W|นอกสถานที่
VIRTUAL|W|เสมือนจริง
WEBINAR|W|สัมมนาออนไลน์
PODCAST|W|พอดแคสต์
NEWSLETTER|W|จดหมายข่าว
BULLETIN|W|ประกาศข่าวสาร
CIRCULAR|W|หนังสือเวียน
DIRECTORY|W|สมุดรายชื่อ
ROSTER|W|ตารางเวรงาน
HEADCOUNT|W|จำนวนพนักงาน
ORGCHART|W|ผังองค์กร
SLOGAN|W|คำขวัญ
MISSION|W|พันธกิจ
VISION|W|วิสัยทัศน์
VALUES|W|ค่านิยม
CULTURE|W|วัฒนธรรมองค์กร
ETHICS|W|จริยธรรม
INTEGRITY|W|ความซื่อสัตย์
OWNERSHIP|W|ความเป็นเจ้าของงาน
INITIATIVE|W|ความคิดริเริ่ม
CREATIVITY|W|ความคิดสร้างสรรค์
INNOVATION|W|นวัตกรรม
DISRUPTION|W|การเปลี่ยนแปลงครั้งใหญ่
PIVOT|W|การปรับเปลี่ยนทิศทาง
SCALE|W|การขยายธุรกิจ
GROWTH|W|การเติบโต
TRACTION|W|แรงขับเคลื่อนธุรกิจ
RUNWAY|W|ระยะเวลาที่เงินทุนพอใช้
VALUATION|W|การประเมินมูลค่า
ROUND|W|รอบระดมทุน
DEMO|W|การสาธิต
ROLLOUT|W|การเปิดใช้งานจริง
ADOPTION|W|การยอมรับใช้งาน
RETENTION|W|การรักษาลูกค้า
CHURN|W|อัตราการเลิกใช้บริการ
CONVERSION|W|อัตราการเปลี่ยนเป็นลูกค้า
FUNNEL|W|ช่องทางการขาย
LEAD|W|ลูกค้าเป้าหมาย
PROSPECT|W|ผู้มีแนวโน้มเป็นลูกค้า
PIPELINE|W|กระบวนการขาย
COMMISSION|W|ค่าคอมมิชชัน
INCENTIVE|W|สิ่งจูงใจ
PERK|W|สิทธิพิเศษ
ALLOWANCE|W|เบี้ยเลี้ยง
STIPEND|W|เงินช่วยเหลือ
GRANT|W|เงินสนับสนุน
SPONSOR|W|ผู้สนับสนุน
DONOR|W|ผู้บริจาค
CHARITY|W|การกุศล
NONPROFIT|W|องค์กรไม่แสวงหากำไร
FOUNDATION|W|มูลนิธิ
CLOCK|W|นาฬิกา
TIMER|W|ตัวจับเวลา
ALARM|W|เสียงเตือน
DESKTOP|W|คอมพิวเตอร์ตั้งโต๊ะ
CABLE|W|สายเคเบิล
CHARGER|W|ที่ชาร์จ
ADAPTER|W|อะแดปเตอร์
ROUTER|W|เราเตอร์
MODEM|W|โมเด็ม
HEADSET|W|หูฟังพร้อมไมค์
SPEAKER|W|ลำโพง
WEBCAM|W|กล้องเว็บแคม
TABLET|W|แท็บเล็ต
SCANNER|W|เครื่องสแกน
SHREDDER|W|เครื่องทำลายเอกสาร
PUSHPIN|W|เข็มหมุด
PAPERCLIP|W|คลิปหนีบกระดาษ
SCISSOR|W|กรรไกร
RULER|W|ไม้บรรทัด
ERASER|W|ยางลบ
NOTEBOOK|W|สมุดบันทึก
DIARY|W|สมุดไดอารี่
PLANNER|W|สมุดวางแผน
ORGANIZER|W|ตัวจัดระเบียบ
LOCKER|W|ตู้ล็อกเกอร์
VAULT|W|ห้องนิรภัย
SAFE|W|ตู้เซฟ
BUZZER|W|กริ่งสัญญาณ
INTERCOM|W|อินเตอร์คอม
PAGER|W|เพจเจอร์
RADIO|W|วิทยุ
CURTAIN|W|ผ้าม่าน
DOOR|W|ประตู
LOCK|W|กุญแจล็อก
HANDLE|W|ที่จับ
HINGE|W|บานพับ
CEILING|W|เพดาน
FLOOR|W|พื้น
PILLAR|W|เสา
COLUMN|W|เสาหลัก
ROOF|W|หลังคา
ENTRANCE|W|ทางเข้า
EXIT|W|ทางออก
HALLWAY|W|ทางเดิน
CORRIDOR|W|ระเบียงทางเดิน
PASSAGE|W|ทางผ่าน
RAMP|W|ทางลาด
FOYER|W|ห้องโถงหน้า
ATRIUM|W|ห้องโถงกลาง
TERRACE|W|ระเบียง
ROOFTOP|W|ดาดฟ้า
BASEMENT|W|ชั้นใต้ดิน
WING|W|ปีกอาคาร
CAMPUS|W|วิทยาเขต
FACILITY|W|สิ่งอำนวยความสะดวก
PREMISES|W|สถานที่
COMPOUND|W|บริเวณอาคาร
ESTATE|W|อสังหาริมทรัพย์
PROPERTY|W|ทรัพย์สิน
LEASE|W|สัญญาเช่า
RENT|W|ค่าเช่า
TENANT|W|ผู้เช่า
LANDLORD|W|เจ้าของที่ดิน
OCCUPANT|W|ผู้ครอบครอง
RESIDENT|W|ผู้พักอาศัย
CARETAKER|W|ผู้ดูแลสถานที่
JANITOR|W|ภารโรง
CLEANER|W|พนักงานทำความสะอาด
CUSTODIAN|W|ผู้ดูแลอาคาร
CONCIERGE|W|พนักงานต้อนรับ
DOORMAN|W|พนักงานเปิดประตู
GUARD|W|ยาม
PATROL|W|การลาดตระเวน
SENSOR|W|เซ็นเซอร์
DETECTOR|W|เครื่องตรวจจับ
SPRINKLER|W|หัวฉีดน้ำดับเพลิง
HYDRANT|W|หัวจ่ายน้ำดับเพลิง
EVACUATION|W|การอพยพ
DRILL|W|การซ้อมหนีไฟ
SIREN|W|เสียงไซเรน
HAZARD|W|อันตราย
CAUTION|W|ข้อควรระวัง
WARNING|W|คำเตือน
GUIDELINE|W|แนวปฏิบัติ
INSPECTOR|W|ผู้ตรวจสอบ
INSPECTION|W|การตรวจสอบ
OUTCOME|W|ผลลัพธ์
IMPACT|W|ผลกระทบ
INSIGHT|W|ข้อมูลเชิงลึก
TREND|W|แนวโน้ม
PATTERN|W|รูปแบบ
PROJECTION|W|การคาดการณ์
ESTIMATE|W|การประมาณการ
ASSESSMENT|W|การประเมิน
EVALUATION|W|การประเมินผล
ONBOARD|W|การปฐมนิเทศ
INDUCTION|W|การอบรมเข้างาน
APPRAISE|W|การประเมินผลงาน
MENTORSHIP|W|การเป็นพี่เลี้ยง
SUCCESSION|W|การสืบทอดตำแหน่ง
RETIREMENT|W|การเกษียณอายุ
DISMISSAL|W|การไล่ออก
GRIEVANCE|W|ข้อร้องทุกข์
ARBITRATE|W|การไกล่เกลี่ย
MEDIATOR|W|ผู้ไกล่เกลี่ย
UNION|W|สหภาพแรงงาน
STRIKE|W|การนัดหยุดงาน
PROTEST|W|การประท้วง
LABOR|W|แรงงาน
WORKFORCE|W|กำลังแรงงาน
RECRUIT|W|การสรรหาบุคลากร
HIRE|W|การจ้างงาน
ONBOARDING|W|การรับพนักงานใหม่
CANDIDATE|W|ผู้สมัครงาน
APPLICANT|W|ผู้สมัคร
REFEREE|W|ผู้อ้างอิง
REFERRAL|W|การแนะนำ
HEADHUNTER|W|นายหน้าจัดหางาน
VACANCY|W|ตำแหน่งว่าง
OPENING|W|ตำแหน่งงานว่าง
POSTING|W|การประกาศงาน
LISTING|W|รายการประกาศ
PORTAL|W|เว็บพอร์ทัล
DASHBOARD|W|แดชบอร์ด
WIDGET|W|วิดเจ็ต
MODULE|W|โมดูล
PLUGIN|W|ปลั๊กอิน
INTERFACE|W|อินเตอร์เฟซ
BROWSER|W|เบราว์เซอร์
TAB|W|แท็บ
LINK|W|ลิงก์
URL|W|ที่อยู่เว็บไซต์
DOMAIN|W|โดเมน
HOSTING|W|บริการโฮสติ้ง
CLOUD|W|คลาวด์
BANDWIDTH|W|แบนด์วิดท์
ENCRYPT|W|การเข้ารหัส
FIREWALL|W|ไฟร์วอลล์
VIRUS|W|ไวรัส
MALWARE|W|มัลแวร์
PATCH|W|แพตช์ซอฟต์แวร์
BUG|W|ข้อผิดพลาดโปรแกรม
DEBUG|W|การแก้ไขบั๊ก
CODE|W|โค้ดโปรแกรม
PROGRAM|W|โปรแกรม
ALGORITHM|W|อัลกอริทึม
FUNCTION|W|ฟังก์ชัน
VARIABLE|W|ตัวแปร
ARRAY|W|อาร์เรย์
LOOP|W|การวนซ้ำ
QUERY|W|การสืบค้นข้อมูล
BACKLOG|W|งานค้าง
SPRINT|W|รอบงานระยะสั้น
STANDUP|W|การประชุมสั้น
RETRO|W|การทบทวนงาน
KANBAN|W|บอร์ดคัมบัง
SCRUM|W|กระบวนการสครัม
AGILE|W|การทำงานแบบยืดหยุ่น
PROCURE|W|การจัดซื้อ
BID|W|การประมูล
TENDER|W|การประกวดราคา
QUOTATION|W|ใบเสนอราคา
PURCHASE|W|การจัดซื้อ
ORDER|W|คำสั่งซื้อ
DISPATCH|W|การจัดส่งของ
LOGISTICS|W|โลจิสติกส์
FLEET|W|กองยานพาหนะ
FORKLIFT|W|รถยก
PALLET|W|พาเลท
CRATE|W|ลังไม้
CARTON|W|กล่องกระดาษ
PACKAGE|W|หีบห่อ
WRAP|W|การห่อของ
SEAL|W|การปิดผนึก
BARCODE|W|บาร์โค้ด
TRACKING|W|การติดตามพัสดุ
CUSTOMS|W|ศุลกากร
TARIFF|W|อัตราภาษีศุลกากร
EXPORT|W|การส่งออก
IMPORT|W|การนำเข้า
TRADE|W|การค้า
COMMERCE|W|พาณิชยกรรม
ECONOMY|W|เศรษฐกิจ
INFLATION|W|เงินเฟ้อ
RECESSION|W|ภาวะเศรษฐกิจถดถอย
EXPANSION|W|การขยายตัว
DOWNSIZE|W|การลดขนาดองค์กร
MERGE|W|การควบรวม
APPLE|F|แอปเปิล
BANANA|F|กล้วย
ORANGE|F|ส้ม
GRAPE|F|องุ่น
MANGO|F|มะม่วง
LEMON|F|มะนาวเหลือง
LIME|F|มะนาว
PEACH|F|ลูกพีช
PLUM|F|พลัม
CHERRY|F|เชอร์รี่
MELON|F|แตงโม
PAPAYA|F|มะละกอ
PINEAPPLE|F|สับปะรด
COCONUT|F|มะพร้าว
STRAWBERRY|F|สตรอว์เบอร์รี
RICE|F|ข้าว
BREAD|F|ขนมปัง
NOODLE|F|บะหมี่
PASTA|F|พาสต้า
SOUP|F|ซุป
SALAD|F|สลัด
CURRY|F|แกงกะหรี่
STEAK|F|สเต็ก
CHICKEN|F|เนื้อไก่
BEEF|F|เนื้อวัว
PORK|F|เนื้อหมู
FISH|F|ปลา
SHRIMP|F|กุ้ง
CRAB|F|ปู
SQUID|F|ปลาหมึก
EGG|F|ไข่
MILK|F|นม
CHEESE|F|ชีส
BUTTER|F|เนย
CREAM|F|ครีม
YOGURT|F|โยเกิร์ต
HONEY|F|น้ำผึ้ง
SUGAR|F|น้ำตาล
SALT|F|เกลือ
PEPPER|F|พริกไทย
SPICE|F|เครื่องเทศ
HERB|F|สมุนไพร
GARLIC|F|กระเทียม
ONION|F|หัวหอม
GINGER|F|ขิง
CHILI|F|พริก
BASIL|F|ใบโหระพา
MINT|F|สะระแหน่
CILANTRO|F|ผักชี
TOMATO|F|มะเขือเทศ
POTATO|F|มันฝรั่ง
CARROT|F|แครอท
CABBAGE|F|กะหล่ำปลี
LETTUCE|F|ผักกาดหอม
CUCUMBER|F|แตงกวา
SPINACH|F|ผักโขม
BROCCOLI|F|บรอกโคลี
PUMPKIN|F|ฟักทอง
EGGPLANT|F|มะเขือยาว
MUSHROOM|F|เห็ด
BEAN|F|ถั่ว
PEANUT|F|ถั่วลิสง
CORN|F|ข้าวโพด
WHEAT|F|ข้าวสาลี
FLOUR|F|แป้ง
DOUGH|F|แป้งนวด
YEAST|F|ยีสต์
CAKE|F|เค้ก
COOKIE|F|คุกกี้
BISCUIT|F|บิสกิต
PIE|F|พาย
PUDDING|F|พุดดิ้ง
PANCAKE|F|แพนเค้ก
WAFFLE|F|วาฟเฟิล
DONUT|F|โดนัท
MUFFIN|F|มัฟฟิน
TOAST|F|การดื่มอวยพร
SANDWICH|F|แซนด์วิช
BURGER|F|เบอร์เกอร์
PIZZA|F|พิซซ่า
TACO|F|ทาโก้
SUSHI|F|ซูชิ
DUMPLING|F|เกี๊ยว
SPRINGROLL|F|ปอเปี๊ยะ
OMELET|F|ไข่เจียว
PORRIDGE|F|โจ๊ก
STEW|F|สตูว์
GRAVY|F|น้ำเกรวี่
SAUCE|F|ซอส
DRESSING|F|น้ำสลัด
VINEGAR|F|น้ำส้มสายชู
SOY|F|ถั่วเหลือง
OIL|F|น้ำมัน
FAT|F|ไขมัน
STARCH|F|แป้ง
BROTH|F|น้ำซุป
SNACK|F|ของว่าง
CANDY|F|ลูกอม
CHOCOLATE|F|ช็อกโกแลต
ICECREAM|F|ไอศกรีม
JELLY|F|เยลลี่
CARAMEL|F|คาราเมล
VANILLA|F|วานิลลา
CINNAMON|F|อบเชย
NUTMEG|F|ลูกจันทน์เทศ
CLOVE|F|กานพลู
CUMIN|F|ยี่หร่า
TURMERIC|F|ขมิ้น
PAPRIKA|F|พริกป่น
MUSTARD|F|มัสตาร์ด
KETCHUP|F|ซอสมะเขือเทศ
MAYO|F|มายองเนส
JAM|F|แยม
SYRUP|F|น้ำเชื่อม
COFFEE|F|กาแฟ
TEA|F|ชา
JUICE|F|น้ำผลไม้
WATER|F|น้ำ
SODA|F|น้ำอัดลม
BEER|F|เบียร์
WINE|F|ไวน์
WHISKEY|F|วิสกี้
COCKTAIL|F|ค็อกเทล
SMOOTHIE|F|สมูทตี้
SHAKE|F|มิลค์เชค
LATTE|F|ลาเต้
ESPRESSO|F|เอสเพรสโซ
MOCHA|F|มอคค่า
CARAFE|F|เหยือกแก้ว
KETTLE|F|กาต้มน้ำ
TEAPOT|F|กาชงชา
MUG|F|แก้วมัค
CUP|F|ถ้วย
GLASS|F|แก้ว
BOTTLE|F|ขวด
STRAW|F|หลอดดูด
PLATE|F|การจัดจาน
BOWL|F|ชาม
SPOON|F|ช้อน
FORK|F|ส้อม
KNIFE|F|มีด
CHOPSTICK|F|ตะเกียบ
NAPKIN|F|ผ้าเช็ดปาก
TRAY|F|ถาด
MENU|F|เมนูอาหาร
RECIPE|F|สูตรอาหาร
INGREDIENT|F|ส่วนผสม
PORTION|F|ส่วนแบ่งอาหาร
SERVING|F|การเสิร์ฟ
APPETIZER|F|อาหารเรียกน้ำย่อย
DESSERT|F|ของหวาน
BREAKFAST|F|อาหารเช้า
DINNER|F|อาหารเย็น
BRUNCH|F|อาหารสาย
BUFFET|F|บุฟเฟต์
CATERING|F|บริการจัดเลี้ยง
RESTAURANT|F|ร้านอาหาร
CAFE|F|ร้านกาแฟ
BAKERY|F|ร้านเบเกอรี่
KITCHEN|F|ห้องครัว
CHEF|F|เชฟ
COOK|F|พ่อครัว
WAITER|F|บริกร
WAITRESS|F|พนักงานเสิร์ฟ
GRILL|F|เตาย่าง
OVEN|F|เตาอบ
STOVE|F|เตา
PAN|F|กระทะ
POT|F|หม้อ
BLENDER|F|เครื่องปั่น
TOASTER|F|เครื่องปิ้งขนมปัง
FRIDGE|F|ตู้เย็น
FREEZER|F|ช่องแช่แข็ง
MICROWAVE|F|ไมโครเวฟ
BOIL|F|การต้ม
FRY|F|การทอด
BAKE|F|การอบ
ROAST|F|เนื้ออบ
GRILLED|F|ย่างแล้ว
STEAM|F|การนึ่ง
MARINATE|F|การหมัก
CHOP|F|การสับ
SLICE|F|ชิ้นหั่น
PEEL|F|เปลือก
MIX|F|การผสม
STIR|F|การคน
WHISK|F|การตี
SEASON|F|การปรุงรส
TASTE|F|รสชาติ
SWEET|F|หวาน
SOUR|F|เปรี้ยว
BITTER|F|ขม
SALTY|F|เค็ม
SPICY|F|เผ็ด
SAVORY|F|รสกลมกล่อม
FRESH|F|สด
RIPE|F|สุก
RAW|F|ดิบ
STALE|F|เก่า ไม่สด
MEAL|F|มื้ออาหาร
DIET|F|อาหารการกิน
VEGETARIAN|F|มังสวิรัติ
VEGAN|F|วีแกน
ORGANIC|F|เกษตรอินทรีย์
GRAIN|F|ธัญพืช
OAT|F|ข้าวโอ๊ต
BARLEY|F|ข้าวบาร์เลย์
LENTIL|F|ถั่วเลนทิล
TOFU|F|เต้าหู้
ALMOND|F|อัลมอนด์
CASHEW|F|เม็ดมะม่วงหิมพานต์
WALNUT|F|วอลนัท
RAISIN|F|ลูกเกด
DATE|F|อินทผลัม
FIG|F|มะเดื่อ
KIWI|F|กีวี
GUAVA|F|ฝรั่ง
DURIAN|F|ทุเรียน
LYCHEE|F|ลิ้นจี่
LONGAN|F|ลำไย
RAMBUTAN|F|เงาะ
TAMARIND|F|มะขาม
POMELO|F|ส้มโอ
PEAR|F|ลูกแพร์
APRICOT|F|แอปริคอต
AVOCADO|F|อะโวคาโด
ZUCCHINI|F|ซูกินี
PLATTER|F|จานเสิร์ฟใหญ่
COURSE|F|มื้ออาหารแต่ละจาน
STARTER|F|อาหารเรียกน้ำย่อย
MAIN|F|อาหารจานหลัก
SIDE|F|อาหารเสริม
COMBO|F|ชุดอาหาร
SET|F|ชุดอาหาร
TAKEOUT|F|อาหารกลับบ้าน
COUNTER|F|เคาน์เตอร์
BAR|F|บาร์เครื่องดื่ม
PATIO|F|ระเบียงร้านอาหาร
VALET|F|บริการจอดรถ
TIP|F|ค่าทิป
BILL|F|บิลค่าอาหาร
CHECK|F|ใบเสร็จร้านอาหาร
SPECIAL|F|เมนูพิเศษ
HOUSE|F|เมนูของร้าน
SOUS|F|ผู้ช่วยเชฟ
BARISTA|F|บาริสต้า
SOMMELIER|F|ผู้เชี่ยวชาญไวน์
MIXOLOGIST|F|นักผสมเครื่องดื่ม
BARTENDER|F|บาร์เทนเดอร์
HOST|F|พนักงานต้อนรับร้านอาหาร
BUSSER|F|พนักงานเก็บโต๊ะ
DISHWASHER|F|เครื่องล้างจาน
BURNER|F|หัวเตา
RANGE|F|เตาทำอาหาร
HOOD|F|เครื่องดูดควัน
COUNTERTOP|F|เคาน์เตอร์ครัว
ICEBOX|F|กล่องน้ำแข็ง
SPICERACK|F|ชั้นวางเครื่องเทศ
TEASET|F|ชุดน้ำชา
TEASPOON|F|ช้อนชา
TABLESPOON|F|ช้อนโต๊ะ
SKILLET|F|กระทะแบน
SAUCEPAN|F|หม้อซอส
STOCKPOT|F|หม้อต้มน้ำซุป
DUTCHOVEN|F|หม้ออบ
CASSEROLE|F|หม้ออบใหญ่
RAMEKIN|F|ถ้วยอบขนาดเล็ก
DECANTER|F|เหยือกไวน์
PITCHER|F|เหยือกน้ำ
GOBLET|F|แก้วมีขา
TUMBLER|F|แก้วทรงกระบอก
FLASK|F|กระติกพกพา
COOLBOX|F|กล่องเย็น
ICEBUCKET|F|ถังใส่น้ำแข็ง
CORKSCREW|F|ที่เปิดไวน์
OPENER|F|ที่เปิดขวด
CANOPENER|F|ที่เปิดกระป๋อง
STRAINER|F|ตะแกรงกรอง
BAGEL|F|เบเกิล
CROISSANT|F|ครัวซองต์
PRETZEL|F|เพรทเซล
CRACKER|F|แครกเกอร์
CHIP|F|มันฝรั่งทอดกรอบ
POPCORN|F|ป๊อปคอร์น
PRETZELS|F|เพรทเซล
GRANOLA|F|กราโนล่า
CEREAL|F|ซีเรียล
OATMEAL|F|ข้าวโอ๊ต
PANCAKES|F|แพนเค้ก
WAFFLES|F|วาฟเฟิล
BACON|F|เบคอน
SAUSAGE|F|ไส้กรอก
HAM|F|แฮม
SALAMI|F|ซาลามี
JERKY|F|เนื้อแดดเดียว
MEATBALL|F|ลูกชิ้น
MEATLOAF|F|มีทโลฟ
BARBECUE|F|บาร์บีคิว
SKEWER|F|ไม้เสียบ
KEBAB|F|เคบับ
STIRFRY|F|ผัด
WOK|F|กระทะจีน
STEAMER|F|ลังถึง
COLANDER|F|กระชอน
LADLE|F|ทัพพี
SPATULA|F|ตะหลิว
TONGS|F|คีมคีบอาหาร
GRATER|F|เครื่องขูด
PEELER|F|มีดปอกเปลือก
ROLLINGPIN|F|ไม้นวดแป้ง
MIXER|F|เครื่องผสม
GRINDER|F|เครื่องบด
JUICER|F|เครื่องคั้นน้ำผลไม้
SIEVE|F|ตะแกรงร่อน
MOLD|F|แม่พิมพ์
APRON|F|ผ้ากันเปื้อน
MITTEN|F|ถุงมือกันความร้อน
PANTRY|F|ห้องเก็บอาหาร
CELLAR|F|ห้องใต้ดินเก็บของ
LARDER|F|ตู้เก็บอาหาร
GROCERY|F|ร้านขายของชำ
STALL|F|แผงขายของ
FARMER|F|ชาวนา ชาวไร่
HARVEST|F|การเก็บเกี่ยว
ORCHARD|F|สวนผลไม้
VINEYARD|F|ไร่องุ่น
FIELD|F|ทุ่งนา
CROP|F|พืชผล
SEED|F|เมล็ดพันธุ์
SPROUT|F|ต้นอ่อน
ROOT|F|ราก
LEAF|F|ใบไม้
STEM|F|ลำต้น
SKIN|F|เปลือกผลไม้
PULP|F|เนื้อผลไม้
PUREE|F|ผลไม้บด
PICKLE|F|ผักดอง
FERMENT|F|การหมัก
BREW|F|การต้มชงเบียร์
DISTILL|F|การกลั่น
INFUSE|F|การชงแช่
STEEP|F|การแช่ชา
BLEND|F|การผสม
GARNISH|F|เครื่องตกแต่งจาน
TOPPING|F|ท็อปปิ้ง
FILLING|F|ไส้ขนม
CRUST|F|เปลือกขนม
BATTER|F|แป้งเปียก
CRUMB|F|เศษขนมปัง
LOAF|F|ก้อนขนมปัง
CHUNK|F|ก้อนใหญ่
CUBE|F|ลูกเต๋า
STRIP|F|ชิ้นเรียวยาว
WEDGE|F|ชิ้นรูปลิ่ม
HELPING|F|ปริมาณเสิร์ฟ
LEFTOVER|F|อาหารเหลือ
MOLDY|F|ขึ้นรา
SPOILED|F|เสีย
EXPIRED|F|หมดอายุ
PRESERVE|F|การถนอมอาหาร
CAN|F|กระป๋อง
JAR|F|ขวดโหล
VACUUM|F|สุญญากาศ
PACKAGING|F|บรรจุภัณฑ์
NATURAL|F|จากธรรมชาติ
ARTIFICIAL|F|สังเคราะห์
ADDITIVE|F|สารเจือปน
FLAVOR|F|รสชาติ
AROMA|F|กลิ่นหอม
TEXTURE|F|เนื้อสัมผัส
CRISPY|F|กรอบ
CRUNCHY|F|กรุบกรอบ
CHEWY|F|เหนียวหนึบ
JUICY|F|ฉ่ำน้ำ
CREAMY|F|เนื้อครีมมี่
FLUFFY|F|ฟูนุ่ม
MOIST|F|ชุ่มชื้น
DRY|F|แห้ง
SOGGY|F|เละแฉะ
BURNT|F|ไหม้
OVERCOOKED|F|สุกเกินไป
SIMMER|F|การเคี่ยวไฟอ่อน
POACH|F|การต้มในน้ำร้อน
SEAR|F|การย่างไฟแรง
BRAISE|F|การตุ๋น
CARAMELIZE|F|การทำให้เป็นคาราเมล
GLAZE|F|การเคลือบน้ำเชื่อม
DRIZZLE|F|การราดซอส
SPRINKLE|F|การโรยหน้า
STUFF|F|การยัดไส้
ROLL|F|การม้วน
FOLD|F|การพับ
KNEAD|F|การนวดแป้ง
WHIP|F|การตีให้ฟู
BEAT|F|การตีส่วนผสม
SIFT|F|การร่อนแป้ง
MEASURE|F|การตวง
WEIGH|F|การชั่งน้ำหนัก
POUR|F|การเท
SCOOP|F|การตักด้วยที่ตัก
SERVE|F|การเสิร์ฟ
GARNISHED|F|ตกแต่งแล้ว
POTLUCK|F|งานเลี้ยงต่างคนต่างเอาอาหารมา
PICNIC|F|ปิกนิก
FEAST|F|งานเลี้ยงใหญ่
BANQUET|F|งานเลี้ยง
CHEERS|F|การชนแก้ว
APPETITE|F|ความอยากอาหาร
CRAVING|F|ความอยากอาหารมาก
HUNGRY|F|หิว
THIRSTY|F|กระหายน้ำ
FULL|F|อิ่ม
STARVING|F|หิวมาก
GLUTTON|F|คนตะกละ
PICKY|F|เลือกกิน
ALLERGIC|F|แพ้อาหาร
INTOLERANT|F|ไม่ทนต่ออาหารบางชนิด
GLUTENFREE|F|ปราศจากกลูเตน
LACTOSE|F|แลคโตส
CALORIE|F|แคลอรี
AIRPORT|T|สนามบิน
AIRPLANE|T|เครื่องบิน
FLIGHT|T|เที่ยวบิน
TICKET|T|ตั๋ว
LUGGAGE|T|กระเป๋าเดินทาง
SUITCASE|T|กระเป๋าเดินทาง
BACKPACK|T|เป้สะพายหลัง
BAGGAGE|T|สัมภาระ
BOARDING|T|การขึ้นเครื่อง
GATE|T|ประตูขึ้นเครื่อง
PILOT|T|นักบิน
CREW|T|ลูกเรือ
CABIN|T|กระท่อม
SEAT|T|ที่นั่ง
AISLE|T|ทางเดินในเครื่องบิน
WINDOW|T|ที่นั่งริมหน้าต่าง
LANDING|T|การลงจอด
TAKEOFF|T|การขึ้นบิน
ITINERARY|T|แผนการเดินทาง
JOURNEY|T|การเดินทาง
TRIP|T|ทริป การเดินทาง
VOYAGE|T|การเดินทางไกล
EXCURSION|T|ทริปสั้น
HOLIDAY|T|วันหยุด
TOURIST|T|นักท่องเที่ยว
TRAVELER|T|ผู้เดินทาง
GUIDE|T|ไกด์นำเที่ยว
MAP|T|แผนที่
COMPASS|T|เข็มทิศ
ROUTE|T|เส้นทาง
ROAD|T|ถนน
HIGHWAY|T|ทางหลวง
BRIDGE|T|สะพาน
TUNNEL|T|อุโมงค์
STATION|T|สถานี
PLATFORM|T|ชานชาลา
TRAIN|T|รถไฟ
SUBWAY|T|รถไฟใต้ดิน
SKYTRAIN|T|รถไฟฟ้า
TRAM|T|รถราง
BUS|T|รถบัส
TAXI|T|แท็กซี่
CAR|T|รถยนต์
VAN|T|รถตู้
TRUCK|T|รถบรรทุก
MOTORCYCLE|T|รถจักรยานยนต์
BICYCLE|T|จักรยาน
SCOOTER|T|สกู๊ตเตอร์
FERRY|T|เรือข้ามฟาก
BOAT|T|เรือ
SHIP|T|เรือใหญ่
CRUISE|T|เรือสำราญ
YACHT|T|เรือยอชต์
HARBOR|T|ท่าเรือ
PORT|T|ท่าเรือ
DOCK|T|ท่าจอดเรือ
ANCHOR|T|สมอเรือ
SAIL|T|ใบเรือ
CAPTAIN|T|กัปตัน
DRIVER|T|คนขับรถ
PASSENGER|T|ผู้โดยสาร
FARE|T|ค่าโดยสาร
TOLL|T|ค่าผ่านทาง
TRAFFIC|T|การจราจร
CONGESTION|T|การจราจรติดขัด
GARAGE|T|โรงรถ
FUEL|T|เชื้อเพลิง
GASOLINE|T|น้ำมันเบนซิน
ENGINE|T|เครื่องยนต์
BRAKE|T|เบรก
STEERING|T|พวงมาลัย
MIRROR|T|กระจกมองข้าง
WHEEL|T|ล้อรถ
TIRE|T|ยางรถ
SPEED|T|ความเร็ว
SIGNAL|T|สัญญาณไฟจราจร
LANE|T|ช่องทางจราจร
CROSSING|T|ทางข้าม
SIDEWALK|T|ทางเท้า
PEDESTRIAN|T|คนเดินถนน
COMMUTER|T|ผู้เดินทางประจำ
RUSHHOUR|T|ชั่วโมงเร่งด่วน
TIMETABLE|T|ตารางเวลา
DELAY|T|ความล่าช้า
CONNECTION|T|การต่อเครื่อง
LAYOVER|T|การแวะพัก
HOTEL|T|โรงแรม
RESORT|T|รีสอร์ท
HOSTEL|T|โฮสเทล
MOTEL|T|โมเต็ล
INN|T|โรงแรมขนาดเล็ก
CHECKOUT|T|การเช็กเอาต์
BOOKING|T|การจองที่พัก
ROOM|T|ห้องพัก
SUITE|T|ห้องสวีท
BALCONY|T|ระเบียง
VIEW|T|วิว ทัศนียภาพ
POOL|T|สระว่ายน้ำ
BEACH|T|ชายหาด
ISLAND|T|เกาะ
MOUNTAIN|T|ภูเขา
VALLEY|T|หุบเขา
FOREST|T|ป่า
JUNGLE|T|ป่าดงดิบ
DESERT|T|ทะเลทราย
LAKE|T|ทะเลสาบ
RIVER|T|แม่น้ำ
WATERFALL|T|น้ำตก
CAVE|T|ถ้ำ
CLIFF|T|หน้าผา
VOLCANO|T|ภูเขาไฟ
GLACIER|T|ธารน้ำแข็ง
CANYON|T|หุบเขาลึก
TEMPLE|T|วัด
MUSEUM|T|พิพิธภัณฑ์
PALACE|T|พระราชวัง
CASTLE|T|ปราสาท
MONUMENT|T|อนุสาวรีย์
LANDMARK|T|สถานที่สำคัญ
ATTRACTION|T|สถานที่ท่องเที่ยว
PANORAMA|T|ทัศนียภาพกว้าง
SOUVENIR|T|ของที่ระลึก
POSTCARD|T|โปสการ์ด
CAMERA|T|กล้องถ่ายรูป
PHOTO|T|รูปถ่าย
SELFIE|T|ภาพถ่ายตัวเอง
EXCHANGE|T|การแลกเงิน
EMERGENCY|T|เหตุฉุกเฉิน
CHECKPOINT|T|จุดตรวจ
ESCALATOR|T|บันไดเลื่อน
TERMINAL|T|อาคารผู้โดยสาร
DEPARTURE|T|ขาออก
ARRIVAL|T|ขาเข้า
LOUNGE|T|ห้องพักผู้โดยสาร
KIOSK|T|บูธจำหน่ายตั๋ว
VENDING|T|ตู้จำหน่ายสินค้า
SIGN|T|ป้ายบอกทาง
DIRECTION|T|ทิศทาง
NORTH|T|ทิศเหนือ
SOUTH|T|ทิศใต้
EAST|T|ทิศตะวันออก
WEST|T|ทิศตะวันตก
DISTANCE|T|ระยะทาง
MILEAGE|T|ระยะทางเป็นไมล์
ALTITUDE|T|ระดับความสูง
CLIMATE|T|ภูมิอากาศ
WEATHER|T|สภาพอากาศ
MONSOON|T|มรสุม
TROPICAL|T|เขตร้อน
ADVENTURE|T|การผจญภัย
EXPLORE|T|การสำรวจ
HIKING|T|การเดินป่า
CAMPING|T|การตั้งแคมป์
TENT|T|เต็นท์
TRAIL|T|เส้นทางเดินป่า
LOCAL|T|คนท้องถิ่น
FESTIVAL|T|เทศกาล
STREET|T|ถนน
ALLEY|T|ตรอกซอย
VILLAGE|T|หมู่บ้าน
TOWN|T|เมืองเล็ก
CITY|T|เมือง
COUNTRY|T|ประเทศ
CONTINENT|T|ทวีป
BORDER|T|พรมแดน
AGENCY|T|บริษัทท่องเที่ยว
OPERATOR|T|ผู้ประกอบการทัวร์
STOPOVER|T|จุดแวะพัก
TRANSIT|T|การเดินทางผ่าน
PASS|T|บัตรผ่าน
ENTRY|T|การเข้าประเทศ
DUTYFREE|T|สินค้าปลอดภาษี
OVERWEIGHT|T|น้ำหนักเกิน
CARRYON|T|กระเป๋าถือขึ้นเครื่อง
CHECKED|T|สัมภาระโหลดใต้เครื่อง
CAROUSEL|T|สายพานรับกระเป๋า
PORTER|T|พนักงานยกกระเป๋า
BELLBOY|T|พนักงานยกกระเป๋าโรงแรม
SHUTTLE|T|รถรับส่ง
LIMOUSINE|T|รถลีมูซีน
CHAUFFEUR|T|คนขับรถส่วนตัว
RENTALCAR|T|รถเช่า
CARPOOL|T|การใช้รถร่วมกัน
RIDESHARE|T|บริการเรียกรถ
TOLLBOOTH|T|ด่านเก็บเงินทางด่วน
SPEEDBUMP|T|เนินชะลอความเร็ว
ROUNDABOUT|T|วงเวียน
OVERPASS|T|สะพานลอย
UNDERPASS|T|ทางลอด
CROSSWALK|T|ทางม้าลาย
SHOULDER|T|ไหล่ทาง
MEDIAN|T|เกาะกลางถนน
SIGNPOST|T|ป้ายบอกทาง
MILEMARKER|T|หลักไมล์
RESTAREA|T|จุดพักรถ
GASSTATION|T|ปั๊มน้ำมัน
CARWASH|T|ล้างรถ
MECHANIC|T|ช่างซ่อมรถ
TOWTRUCK|T|รถลาก
BREAKDOWN|T|รถเสีย
PUNCTURE|T|ยางรั่ว
SPARE|T|ยางอะไหล่
JACK|T|แม่แรง
JUMPSTART|T|การพ่วงแบตเตอรี่
ODOMETER|T|มาตรวัดระยะทาง
HORN|T|แตรรถ
WIPER|T|ที่ปัดน้ำฝน
HEADLIGHT|T|ไฟหน้ารถ
TAILLIGHT|T|ไฟท้ายรถ
TRUNK|T|กระโปรงท้ายรถ
BUMPER|T|กันชนรถ
EXHAUST|T|ท่อไอเสีย
MUFFLER|T|ท่อไอเสีย
SUSPENSION|T|ระบบกันสะเทือน
IGNITION|T|ระบบจุดระเบิด
CLUTCH|T|คลัตช์
GEARBOX|T|เกียร์รถ
EXPLORER|T|นักสำรวจ
NAVIGATOR|T|นักนำทาง
EXPEDITION|T|การเดินทางสำรวจ
SAFARI|T|ซาฟารี
PILGRIMAGE|T|การแสวงบุญ
CAMPSITE|T|พื้นที่ตั้งแคมป์
COTTAGE|T|บ้านพักตากอากาศ
CHALET|T|บ้านพักบนภูเขา
BUNGALOW|T|บ้านชั้นเดียว
VILLA|T|วิลล่า
APARTMENT|T|อพาร์ตเมนต์
CONDO|T|คอนโด
DORMITORY|T|หอพัก
CAMPER|T|รถบ้าน
CARAVAN|T|คาราวาน
TRAILER|T|รถพ่วง
RICKSHAW|T|รถลาก
TUKTUK|T|ตุ๊กตุ๊ก
GONDOLA|T|เรือกอนโดลา
CANOE|T|เรือแคนู
KAYAK|T|เรือคายัค
RAFT|T|แพ
SUBMARINE|T|เรือดำน้ำ
HELICOPTER|T|เฮลิคอปเตอร์
GLIDER|T|เครื่องร่อน
BALLOON|T|บอลลูน
ROCKET|T|จรวด
MONORAIL|T|รถไฟรางเดี่ยว
CABLECAR|T|กระเช้าไฟฟ้า
FUNICULAR|T|รถรางลาดชัน
CONVEYOR|T|สายพานลำเลียง
TROLLEY|T|รถเข็นสัมภาระ
CART|T|รถเข็น
WAGON|T|เกวียน
CARRIAGE|T|รถม้า
CHARIOT|T|รถศึก
SLEIGH|T|เลื่อนหิมะ
SKI|T|สกี
SNOWBOARD|T|สโนว์บอร์ด
SLED|T|เลื่อน
ICESKATE|T|สเก็ตน้ำแข็ง
SURFBOARD|T|กระดานโต้คลื่น
PADDLE|T|ไม้พาย
OAR|T|ไม้กรรเชียง
LIFEJACKET|T|เสื้อชูชีพ
HELMET|T|หมวกกันน็อก
GOGGLES|T|แว่นตากันลม
SUNSCREEN|T|ครีมกันแดด
UMBRELLA|C|ร่ม
RAINCOAT|C|เสื้อกันฝน
POLE|T|ไม้เท้าเดินป่า
ROPE|T|เชือก
FLASHLIGHT|T|ไฟฉาย
LANTERN|T|ตะเกียง
BINOCULARS|T|กล้องส่องทางไกล
TELESCOPE|T|กล้องโทรทรรศน์
SLEEPBAG|T|ถุงนอน
HAMMOCK|T|เปลญวน
COOLER|T|กระติกเก็บความเย็น
THERMOS|T|กระติกน้ำร้อน
CANTEEN|T|กระติกน้ำ
FIREWOOD|T|ฟืน
CAMPFIRE|T|กองไฟ
MATCHES|T|ไม้ขีดไฟ
LIGHTER|T|ไฟแช็ก
KNAPSACK|T|เป้สะพายหลัง
POUCH|T|ถุงเล็ก
WALLET|C|กระเป๋าสตางค์
PURSE|C|กระเป๋าถือ
BELT|C|เข็มขัด
BOOTS|C|รองเท้าบูท
SANDALS|C|รองเท้าแตะ
POCKET|C|กระเป๋าเสื้อ
JACKET|C|เสื้อแจ็กเก็ต
SCARF|C|ผ้าพันคอ
GLOVES|C|ถุงมือ
CAP|C|หมวกแก๊ป
HAT|C|หมวก
SUNGLASSES|C|แว่นกันแดด
WATCH|C|นาฬิกาข้อมือ
TRAVELPLUG|T|ปลั๊กแปลงไฟ
CONVERTER|T|ตัวแปลงไฟฟ้า
POWERBANK|T|แบตสำรอง
SIMCARD|T|ซิมการ์ด
ROAMING|T|บริการโรมมิ่ง
TRANSLATOR|T|เครื่องแปลภาษา
PHRASEBOOK|T|หนังสือวลีสนทนา
DICTIONARY|T|พจนานุกรม
LANGUAGE|T|ภาษา
GREETING|T|การทักทาย
ETIQUETTE|T|มารยาท
CUSTOM|T|ประเพณี
TRADITION|T|ธรรมเนียม
RITUAL|T|พิธีกรรม
CEREMONY|T|พิธี
PARADE|T|ขบวนพาเหรด
CARNIVAL|T|งานรื่นเริง
FAIR|T|งานออกร้าน
SHOW|T|การแสดง
CONCERT|T|คอนเสิร์ต
THEATER|T|โรงละคร
CINEMA|T|โรงภาพยนตร์
GALLERY|T|หอศิลป์
ZOO|T|สวนสัตว์
AQUARIUM|T|พิพิธภัณฑ์สัตว์น้ำ
PARK|T|สวนสาธารณะ
GARDEN|T|สวน
PLAZA|T|ลานกว้าง
SQUARE|T|จัตุรัส
BOULEVARD|T|ถนนสายใหญ่
AVENUE|T|ถนนใหญ่
PROMENADE|T|ทางเดินริมทะเล
PIER|T|ท่าเทียบเรือ
WHARF|T|ท่าเรือ
JETTY|T|สะพานท่าเรือ
LIGHTHOUSE|T|ประภาคาร
COASTLINE|T|แนวชายฝั่ง
SHORE|T|ชายฝั่ง
BAY|T|อ่าว
GULF|T|อ่าวใหญ่
STRAIT|T|ช่องแคบ
PENINSULA|T|คาบสมุทร
REEF|T|แนวปะการัง
LAGOON|T|ทะเลสาบน้ำเค็ม
DUNE|T|เนินทราย
OASIS|T|โอเอซิส
PLATEAU|T|ที่ราบสูง
PLAIN|T|ที่ราบ
MEADOW|T|ทุ่งหญ้า
PASTURE|T|ทุ่งเลี้ยงสัตว์
GROVE|T|สวนป่าเล็ก
SUMMIT|T|ยอดเขา
PEAK|T|จุดสูงสุด
SLOPE|T|ทางลาดชัน
RIDGE|T|สันเขา
BASECAMP|T|ค่ายฐาน
DOCTOR|H|แพทย์
NURSE|H|พยาบาล
HOSPITAL|H|โรงพยาบาล
CLINIC|H|คลินิก
PHARMACY|H|ร้านขายยา
MEDICINE|H|ยา
CAPSULE|H|ยาแคปซูล
INJECTION|H|การฉีดยา
VACCINE|H|วัคซีน
DOSAGE|H|ปริมาณยา
SYMPTOM|H|อาการ
DIAGNOSIS|H|การวินิจฉัย
TREATMENT|H|การรักษา
THERAPY|H|การบำบัด
SURGERY|H|การผ่าตัด
OPERATION|H|การผ่าตัด
RECOVERY|H|การฟื้นฟู
PATIENT|H|ผู้ป่วย
ILLNESS|H|ความเจ็บป่วย
DISEASE|H|โรค
INFECTION|H|การติดเชื้อ
BACTERIA|H|แบคทีเรีย
FEVER|H|ไข้
COUGH|H|อาการไอ
COLD|H|หวัด
FLU|H|ไข้หวัดใหญ่
HEADACHE|H|ปวดหัว
TOOTHACHE|H|ปวดฟัน
BACKACHE|H|ปวดหลัง
ALLERGY|H|การแพ้
ASTHMA|H|โรคหอบหืด
DIABETES|H|โรคเบาหวาน
CANCER|H|โรคมะเร็ง
STROKE|H|โรคหลอดเลือดสมอง
HEARTBEAT|H|การเต้นของหัวใจ
PULSE|H|ชีพจร
BLOOD|H|เลือด
PRESSURE|H|ความดัน
OXYGEN|H|ออกซิเจน
BREATH|H|ลมหายใจ
BREATHE|H|การหายใจ
LUNG|H|ปอด
HEART|H|หัวใจ
LIVER|H|ตับ
KIDNEY|H|ไต
STOMACH|H|กระเพาะอาหาร
MUSCLE|H|กล้ามเนื้อ
BONE|H|กระดูก
NERVE|H|เส้นประสาท
BRAIN|H|สมอง
SPINE|H|กระดูกสันหลัง
JOINT|H|ข้อต่อ
TENDON|H|เอ็น
ARTERY|H|หลอดเลือดแดง
VEIN|H|หลอดเลือดดำ
CELL|H|เซลล์
TISSUE|H|เนื้อเยื่อ
IMMUNE|H|ภูมิคุ้มกัน
HORMONE|H|ฮอร์โมน
VITAMIN|H|วิตามิน
MINERAL|H|แร่ธาตุ
PROTEIN|H|โปรตีน
CALCIUM|H|แคลเซียม
NUTRITION|H|โภชนาการ
EXERCISE|H|การออกกำลังกาย
FITNESS|H|ความฟิต
WORKOUT|H|การออกกำลังกาย
STRETCH|H|การยืดกล้ามเนื้อ
JOGGING|H|การวิ่งเหยาะ
RUNNING|H|การวิ่ง
SWIMMING|H|การว่ายน้ำ
YOGA|H|โยคะ
GYM|H|ยิม ฟิตเนส
TRAINER|H|ผู้ฝึกสอน
WEIGHT|H|น้ำหนัก
HEIGHT|H|ส่วนสูง
OBESITY|H|โรคอ้วน
STRESS|H|ความเครียด
ANXIETY|H|ความวิตกกังวล
DEPRESSION|H|ภาวะซึมเศร้า
INSOMNIA|H|การนอนไม่หลับ
SLEEP|H|การนอนหลับ
FATIGUE|H|ความเหนื่อยล้า
ENERGY|H|พลังงาน
RELAX|H|การผ่อนคลาย
MEDITATE|H|การทำสมาธิ
THERAPIST|H|นักบำบัด
COUNSELOR|H|ที่ปรึกษา
PSYCHOLOGY|H|จิตวิทยา
DENTIST|H|ทันตแพทย์
DENTAL|H|เกี่ยวกับฟัน
TOOTH|H|ฟัน
GUM|H|เหงือก
BRACES|H|เหล็กจัดฟัน
EYE|H|ดวงตา
GLASSES|H|แว่นตา
HEARING|H|การได้ยิน
EAR|H|หู
THROAT|H|ลำคอ
NOSE|H|จมูก
WOUND|H|บาดแผล
INJURY|H|การบาดเจ็บ
BRUISE|H|รอยฟกช้ำ
FRACTURE|H|กระดูกหัก
SPRAIN|H|ข้อเคล็ด
BANDAGE|H|ผ้าพันแผล
GAUZE|H|ผ้าก๊อซ
STITCH|H|การเย็บแผล
SCAR|H|รอยแผลเป็น
BLEED|H|การมีเลือดออก
BRUISED|H|ฟกช้ำ
SWOLLEN|H|บวม
AMBULANCE|H|รถพยาบาล
FIRSTAID|H|การปฐมพยาบาล
CPR|H|การช่วยฟื้นคืนชีพ
STRETCHER|H|เปลหาม
WHEELCHAIR|H|รถเข็นผู้ป่วย
CRUTCH|H|ไม้ค้ำยัน
SYRINGE|H|เข็มฉีดยา
CHECKUP|H|การตรวจสุขภาพ
SCREENING|H|การตรวจคัดกรอง
XRAY|H|เอกซเรย์
ULTRASOUND|H|อัลตราซาวนด์
LAB|H|ห้องปฏิบัติการ
RESULT|H|ผลตรวจ
HEALTHY|H|สุขภาพดี
SICK|H|ป่วย
PAIN|H|ความเจ็บปวด
ACHE|H|อาการปวด
ITCH|H|อาการคัน
RASH|H|ผื่น
NAUSEA|H|อาการคลื่นไส้
VOMIT|H|การอาเจียน
DIARRHEA|H|ท้องเสีย
DIZZY|H|เวียนหัว
FAINT|H|การเป็นลม
SEIZURE|H|อาการชัก
PARALYSIS|H|อัมพาต
DISABILITY|H|ความพิการ
REHAB|H|การบำบัด
MASSAGE|H|การนวด
HYGIENE|H|สุขอนามัย
SANITIZE|H|การฆ่าเชื้อ
DISINFECT|H|การฆ่าเชื้อโรค
MASK|H|หน้ากากอนามัย
GLOVE|H|ถุงมือ
QUARANTINE|H|การกักตัว
EPIDEMIC|H|โรคระบาด
PANDEMIC|H|โรคระบาดใหญ่
OUTBREAK|H|การระบาด
IMMUNITY|H|ภูมิคุ้มกัน
ANTIBODY|H|แอนติบอดี
ANTIBIOTIC|H|ยาปฏิชีวนะ
PAINKILLER|H|ยาแก้ปวด
ASPIRIN|H|แอสไพริน
INSULIN|H|อินซูลิน
METABOLISM|H|เมแทบอลิซึม
DIGESTION|H|การย่อยอาหาร
PREGNANCY|H|การตั้งครรภ์
NEWBORN|H|ทารกแรกเกิด
INFANT|H|ทารก
TODDLER|H|เด็กวัยหัดเดิน
ELDERLY|H|ผู้สูงอายุ
CAREGIVER|H|ผู้ดูแล
WARD|H|หอผู้ป่วย
ICU|H|หอผู้ป่วยวิกฤต
PILL|H|ยาเม็ด
DOSE|H|ปริมาณยา
DRUG|H|ยารักษาโรค
SPRAY|H|ยาพ่น
DROPS|H|ยาหยอด
LOTION|H|โลชั่นทาผิว
OINTMENT|H|ยาขี้ผึ้ง
BALM|H|ยาหม่อง
GEL|H|เจลทายา
PLASTER|H|พลาสเตอร์ปิดแผล
SLING|H|ผ้าคล้องแขน
SPLINT|H|เฝือกดาม
CAST|H|เฝือกปูน
BRACE|H|อุปกรณ์พยุง
INHALER|H|เครื่องพ่นยา
ALCOHOL|H|แอลกอฮอล์
STERILE|H|ปราศจากเชื้อ
HYGIENIC|H|ถูกสุขอนามัย
CLEAN|H|สะอาด
GERM|H|เชื้อโรค
MICROBE|H|จุลชีพ
PARASITE|H|ปรสิต
FUNGUS|H|เชื้อรา
SPORE|H|สปอร์เชื้อรา
EXAM|H|การตรวจร่างกาย
TEST|H|การทดสอบ
VISIT|H|การไปพบแพทย์
CONSULT|H|การปรึกษาแพทย์
ADVICE|H|คำแนะนำแพทย์
EXPIRY|H|วันหมดอายุ
BATCH|H|ล็อตการผลิต
GENERIC|H|ยาสามัญ
ACTIVE|H|สารออกฤทธิ์
SIDEEFFECT|H|ผลข้างเคียง
OVERDOSE|H|การใช้ยาเกินขนาด
UNDERDOSE|H|การใช้ยาน้อยเกินไป
REFILL|H|การเติมยา
PHARMACIST|H|เภสัชกร
PRESCRIBE|H|การสั่งยา
DISPENSE|H|การจ่ายยา
ADMINISTER|H|การให้ยา
TOPICAL|H|ยาใช้ภายนอก
ORAL|H|ยารับประทาน
INHALED|H|ยาสูด
TOPICALLY|H|ทาภายนอก
SYSTEMIC|H|ทั่วร่างกาย
LOCALIZED|H|เฉพาะจุด
FLAREUP|H|อาการกำเริบ
EPISODE|H|ช่วงอาการกำเริบ
TRIGGER|H|ตัวกระตุ้นอาการ
ONSET|H|การเริ่มมีอาการ
PROGNOSIS|H|การพยากรณ์โรค
OUTLOOK|H|แนวโน้มอาการ
SEVERITY|H|ความรุนแรงของโรค
MILD|H|อาการเล็กน้อย
MODERATE|H|อาการปานกลาง
SEVERE|H|อาการรุนแรง
CRITICAL|H|วิกฤต
STABLE|H|อาการคงที่
IMPROVING|H|อาการดีขึ้น
WORSENING|H|อาการแย่ลง
CURE|H|การรักษาให้หาย
HEAL|H|การสมานแผล
MEND|H|การซ่อมแซมร่างกาย
RESTORE|H|การฟื้นฟู
REGAIN|H|การกลับคืนสภาพ
STRENGTHEN|H|การเสริมความแข็งแรง
BOOST|H|การเสริมสร้าง
SUPPORT|H|การสนับสนุนสุขภาพ
MAINTAIN|H|การรักษาสภาพ
PREVENT|H|การป้องกัน
PROTECT|H|การป้องกันโรค
SHIELD|H|การป้องกัน
TRACK|H|การติดตามสุขภาพ
LOG|H|การจดบันทึก
APP|H|แอปสุขภาพ
WEARABLE|H|อุปกรณ์สวมใส่ติดตามสุขภาพ
SURGEON|H|ศัลยแพทย์
PODIATRIST|H|หมอเท้า
ANESTHESIA|H|ยาสลบ
OUTPATIENT|H|ผู้ป่วยนอก
INPATIENT|H|ผู้ป่วยใน
WAITLIST|H|รายชื่อรอคิว
TRIAGE|H|การคัดแยกผู้ป่วย
VITALS|H|สัญญาณชีพ
RECORD|H|บันทึกทางการแพทย์
HISTORY|H|ประวัติการรักษา
REACTION|H|ปฏิกิริยาแพ้
ADDICTION|H|การติด
RELAPSE|H|การกลับมาป่วยซ้ำ
REMISSION|H|ระยะสงบของโรค
CHRONIC|H|เรื้อรัง
ACUTE|H|เฉียบพลัน
BENIGN|H|ไม่ร้ายแรง
MALIGNANT|H|เนื้อร้าย
TUMOR|H|เนื้องอก
CYST|H|ถุงน้ำ
ULCER|H|แผลในกระเพาะ
LESION|H|รอยโรค
SWELLING|H|อาการบวม
NUMBNESS|H|อาการชา
TINGLING|H|อาการเสียวซ่า
CRAMP|H|ตะคริว
SPASM|H|อาการเกร็ง
TREMOR|H|อาการสั่น
PARALYZED|H|เป็นอัมพาต
COMA|H|ภาวะโคม่า
CONSCIOUS|H|มีสติ
VENTILATOR|H|เครื่องช่วยหายใจ
CATHETER|H|สายสวน
IVDRIP|H|น้ำเกลือ
TRANSPLANT|H|การปลูกถ่ายอวัยวะ
IMPLANT|H|การฝังอุปกรณ์
PROSTHETIC|H|อวัยวะเทียม
ORTHOPEDIC|H|เกี่ยวกับกระดูก
OSTEOPATH|H|แพทย์กระดูก
PODIATRY|H|ศัลยศาสตร์เท้า
OPTICIAN|H|ช่างแว่นตา
DIETITIAN|H|นักกำหนดอาหาร
MIDWIFE|H|ผดุงครรภ์
UROLOGIST|H|แพทย์ระบบทางเดินปัสสาวะ
ONCOLOGIST|H|แพทย์มะเร็งวิทยา
VIROLOGIST|H|นักไวรัสวิทยา
WELLNESS|H|สุขภาวะ
LIFESTYLE|H|วิถีชีวิต
HABIT|H|นิสัย
POSTURE|H|ท่าทาง
STAMINA|H|ความอดทน
ENDURANCE|H|ความทนทาน
STRENGTH|H|ความแข็งแรง
AGILITY|H|ความคล่องตัว
REFLEX|H|ปฏิกิริยาสะท้อน
DIGESTIVE|H|เกี่ยวกับการย่อยอาหาร
SKELETAL|H|เกี่ยวกับโครงกระดูก
MUSCULAR|H|เกี่ยวกับกล้ามเนื้อ
GLAND|H|ต่อม
THYROID|H|ต่อมไทรอยด์
PANCREAS|H|ตับอ่อน
BLADDER|H|กระเพาะปัสสาวะ
INTESTINE|H|ลำไส้
COLON|H|ลำไส้ใหญ่
ESOPHAGUS|H|หลอดอาหาร
LARYNX|H|กล่องเสียง
TRACHEA|H|หลอดลม
DIAPHRAGM|H|กะบังลม
RIBCAGE|H|ซี่โครง
PELVIS|H|กระดูกเชิงกราน
SKULL|H|กะโหลกศีรษะ
VERTEBRA|H|กระดูกสันหลังชิ้น
CARTILAGE|H|กระดูกอ่อน
LIGAMENT|H|เอ็นยึดข้อ
MARROW|H|ไขกระดูก
PLASMA|H|พลาสมาเลือด
PLATELET|H|เกล็ดเลือด
HEMOGLOBIN|H|ฮีโมโกลบิน
GLUCOSE|H|น้ำตาลกลูโคส
ENZYME|H|เอนไซม์
ANTIGEN|H|แอนติเจน
FIBER|H|ใยอาหาร
CARB|H|คาร์โบไฮเดรต
SUPPLEMENT|H|อาหารเสริม
PROBIOTIC|H|โพรไบโอติก
HAPPY|E|มีความสุข
SAD|E|เศร้า
ANGRY|E|โกรธ
AFRAID|E|กลัว
SCARED|E|หวาดกลัว
EXCITED|E|ตื่นเต้น
BORED|E|เบื่อหน่าย
TIRED|E|เหนื่อย
CALM|E|สงบ
NERVOUS|E|ประหม่า
WORRIED|E|กังวล
ANXIOUS|E|วิตกกังวล
RELAXED|E|ผ่อนคลาย
PROUD|E|ภาคภูมิใจ
ASHAMED|E|อับอาย
GUILTY|E|รู้สึกผิด
JEALOUS|E|อิจฉา
ENVIOUS|E|อิจฉาริษยา
LONELY|E|เหงา
CONFUSED|E|สับสน
SURPRISED|E|ประหลาดใจ
SHOCKED|E|ตกใจ
AMAZED|E|ทึ่ง
CURIOUS|E|อยากรู้อยากเห็น
INTERESTED|E|สนใจ
FRUSTRATED|E|หงุดหงิด
ANNOYED|E|รำคาญ
IRRITATED|E|หงุดหงิด
UPSET|E|ไม่พอใจ
STRESSED|E|เครียด
CONTENT|E|พอใจ
SATISFIED|E|พึงพอใจ
GRATEFUL|E|ซาบซึ้งใจ
THANKFUL|E|ขอบคุณ
HOPEFUL|E|มีความหวัง
OPTIMISTIC|E|มองโลกในแง่ดี
CONFIDENT|E|มั่นใจ
INSECURE|E|ไม่มั่นใจ
BRAVE|E|กล้าหาญ
COWARDLY|E|ขี้ขลาด
SHY|E|ขี้อาย
REGRET|E|เสียใจภายหลัง
REMORSE|E|สำนึกผิด
SYMPATHY|E|ความเห็นอกเห็นใจ
EMPATHY|E|ความเข้าใจความรู้สึกผู้อื่น
COMPASSION|E|ความเมตตา
KINDNESS|E|ความใจดี
LOVE|E|ความรัก
AFFECTION|E|ความรักใคร่
ADORE|E|การรักใคร่
HATE|E|ความเกลียด
DISGUST|E|ความรังเกียจ
FEAR|E|ความกลัว
JOY|E|ความสุข
DELIGHT|E|ความปีติยินดี
PLEASURE|E|ความพึงพอใจ
MISERY|E|ความทุกข์ยาก
SORROW|E|ความเศร้าโศก
GRIEF|E|ความโศกเศร้า
DESPAIR|E|ความสิ้นหวัง
PANIC|E|ความตื่นตระหนก
TERROR|E|ความหวาดกลัวอย่างมาก
DREAD|E|ความหวาดหวั่น
RELIEF|E|ความโล่งใจ
COMFORT|E|ความสบายใจ
PEACE|E|ความสงบสุข
HARMONY|E|ความกลมกลืน
TENSION|E|ความตึงเครียด
BURDEN|E|ภาระใจ
PASSION|E|ความหลงใหล
ENTHUSIASM|E|ความกระตือรือร้น
EAGER|E|กระตือรือร้น
MOTIVATED|E|มีแรงจูงใจ
INSPIRED|E|ได้รับแรงบันดาลใจ
DETERMINED|E|มุ่งมั่น
STUBBORN|E|ดื้อรั้น
IMPATIENT|E|ใจร้อน
CAUTIOUS|E|ระมัดระวัง
CARELESS|E|ประมาท
GENTLE|E|อ่อนโยน
HARSH|E|รุนแรง กระด้าง
FRIENDLY|E|เป็นมิตร
HOSTILE|E|เป็นปรปักษ์
GENEROUS|E|ใจกว้าง
SELFISH|E|เห็นแก่ตัว
HONEST|E|ซื่อสัตย์
DISHONEST|E|ไม่ซื่อสัตย์
LOYAL|E|ภักดี
TRUST|E|ความไว้วางใจ
DOUBT|E|ความสงสัย
SUSPICION|E|ความสงสัยไม่ไว้ใจ
BETRAYAL|E|การทรยศ
FORGIVE|E|การให้อภัย
APOLOGIZE|E|การขอโทษ
COMPLAIN|E|การบ่น
CRY|E|การร้องไห้
LAUGH|E|การหัวเราะ
SMILE|E|การยิ้ม
FROWN|E|การขมวดคิ้ว
SCREAM|E|การกรีดร้อง
SHOUT|E|การตะโกน
WHISPER|E|การกระซิบ
SIGH|E|การถอนหายใจ
YAWN|E|การหาว
TREMBLE|E|การสั่น
BLUSH|E|การหน้าแดง
SMIRK|E|การยิ้มเยาะ
GRIN|E|การยิ้มกว้าง
MOOD|E|อารมณ์
TEMPER|E|อารมณ์ฉุนเฉียว
ATTITUDE|E|ทัศนคติ
CHARACTER|E|อุปนิสัย
SENSITIVE|E|อ่อนไหว
EMOTIONAL|E|เจ้าอารมณ์
RATIONAL|E|มีเหตุผล
LOGICAL|E|เป็นตรรกะ
INTUITIVE|E|ใช้สัญชาตญาณ
CHEERFUL|E|ร่าเริง
GLOOMY|E|หม่นหมอง
MISERABLE|E|ทุกข์ยาก
EUPHORIC|E|ปีติสุขอย่างมาก
ECSTATIC|E|ปีติยินดีอย่างสุดขีด
TOUCHED|E|ซาบซึ้งใจ
MOVED|E|รู้สึกประทับใจ
MOTIVATION|E|แรงจูงใจ
WILLPOWER|E|พลังใจ
SELFESTEEM|E|ความภาคภูมิใจในตนเอง
SELFWORTH|E|คุณค่าในตนเอง
VULNERABLE|E|เปราะบาง
RESILIENT|E|ยืดหยุ่นทางใจ
STRONG|E|เข้มแข็ง
WEAK|E|อ่อนแอ
BRAVERY|E|ความกล้าหาญ
COURAGE|E|ความกล้า
PANICKED|E|ตื่นตระหนก
STARTLED|E|สะดุ้งตกใจ
AMUSED|E|สนุกสนาน
FASCINATED|E|หลงใหล
INTRIGUED|E|สนใจใคร่รู้
PUZZLED|E|งุนงง
BEWILDERED|E|งุนงงสับสน
AWKWARD|E|อึดอัด
UNEASY|E|ไม่สบายใจ
RESTLESS|E|กระวนกระวาย
AGITATED|E|กระวนกระวายใจ
FURIOUS|E|โกรธจัด
OUTRAGED|E|โกรธเกรี้ยว
RESENTFUL|E|ไม่พอใจแค้นเคือง
NOSTALGIC|E|คิดถึงอดีต
HOMESICK|E|คิดถึงบ้าน
LONGING|E|ความโหยหา
YEARNING|E|ความปรารถนา
BOREDOM|E|ความเบื่อหน่าย
APATHY|E|ความเฉยเมย
GLAD|E|ดีใจ
MERRY|E|ร่าเริงสนุกสนาน
JOLLY|E|เบิกบานใจ
JOVIAL|E|ร่าเริง
GLEEFUL|E|ปีติยินดี
ELATED|E|ปลาบปลื้ม
THRILLED|E|ตื่นเต้นดีใจ
OVERJOYED|E|ดีใจสุดขีด
BLISSFUL|E|เปี่ยมสุข
RADIANT|E|เปล่งประกายความสุข
GLOWING|E|เรืองรองด้วยความสุข
BEAMING|E|ยิ้มแย้มแจ่มใส
PLEASED|E|พอใจ
GRATIFIED|E|อิ่มเอมใจ
FULFILLED|E|รู้สึกเติมเต็ม
TRIUMPHANT|E|รู้สึกมีชัยชนะ
VICTORIOUS|E|รู้สึกได้รับชัยชนะ
EMPOWERED|E|รู้สึกมีพลัง
UPLIFTED|E|รู้สึกดีขึ้น
ENCOURAGED|E|ได้รับกำลังใจ
REASSURED|E|อุ่นใจขึ้น
CONSOLED|E|ได้รับการปลอบใจ
COMFORTED|E|รู้สึกสบายใจ
SOOTHED|E|รู้สึกผ่อนคลาย
CALMED|E|สงบลง
PACIFIED|E|ระงับความโกรธ
MOLLIFIED|E|ใจเย็นลง
APPEASED|E|พอใจขึ้น
SATIATED|E|อิ่มเอมเต็มที่
YEARNFUL|E|เต็มไปด้วยความโหยหา
WISTFUL|E|อาลัยอาวรณ์
MELANCHOLY|E|เศร้าสร้อย
SOMBER|E|เศร้าหมอง
MOURNFUL|E|โศกเศร้า
DEJECTED|E|หดหู่ใจ
DOWNCAST|E|ท้อแท้ใจ
DESPONDENT|E|สิ้นหวังท้อแท้
DEFEATED|E|รู้สึกพ่ายแพ้
HOPELESS|E|หมดหวัง
HELPLESS|E|รู้สึกช่วยเหลือตัวเองไม่ได้
POWERLESS|E|รู้สึกไร้อำนาจ
TRAPPED|E|รู้สึกติดกับดัก
STUCK|E|รู้สึกจนตรอก
CONFINED|E|รู้สึกถูกจำกัด
RESTRICTED|E|รู้สึกถูกจำกัดสิทธิ์
SUPPRESSED|E|ถูกกดข่มความรู้สึก
REPRESSED|E|เก็บกดความรู้สึก
BOTTLED|E|เก็บกดไว้ในใจ
RELEASED|E|ปลดปล่อยความรู้สึก
UNBURDENED|E|ปลดเปลื้องภาระใจ
LIBERATED|E|เป็นอิสระทางใจ
FREED|E|เป็นอิสระ
ENERGIZED|E|มีพลังงาน
RENEWED|E|รู้สึกเริ่มต้นใหม่
AWAKENED|E|ตื่นรู้
REALIZED|E|ตระหนักได้
UNDERSTOOD|E|เข้าใจ
CLARIFIED|E|กระจ่างชัดขึ้น
CERTAIN|E|มั่นใจแน่นอน
UNCERTAIN|E|ไม่แน่ใจ
AMBIVALENT|E|รู้สึกสองจิตสองใจ
TORN|E|ลังเลใจ
CONFLICTED|E|รู้สึกขัดแย้งในใจ
DIVIDED|E|รู้สึกแบ่งแยกในใจ
SETTLED|E|ใจนิ่งลง
RESOLVED|E|คลี่คลายใจได้
SERENE|E|สงบเยือกเย็น
TRANQUIL|E|สงบนิ่ง
PLACID|E|เงียบสงบ
EASE|E|ความสบายใจ
COZY|E|อบอุ่นสบาย
WARMTH|E|ความอบอุ่นใจ
TENDERNESS|E|ความอ่อนโยน
FONDNESS|E|ความชื่นชอบ
LIKING|E|ความชอบ
CRUSH|E|การแอบชอบ
ROMANCE|E|ความรักโรแมนติก
INTIMACY|E|ความสนิทสนม
BONDING|E|ความผูกพัน
BELONGING|E|ความรู้สึกเป็นส่วนหนึ่ง
ACCEPTANCE|E|การยอมรับ
REJECTION|E|การถูกปฏิเสธ
ISOLATION|E|ความโดดเดี่ยว
SOLITUDE|E|ความสันโดษ
ALIENATION|E|ความรู้สึกแปลกแยก
ESTRANGED|E|ห่างเหิน
DETACHED|E|เฉยชา ไม่ผูกพัน
NUMB|E|ชาไร้ความรู้สึก
BLANK|E|ว่างเปล่าทางใจ
DAZED|E|งงงวย
STUNNED|E|ตะลึง
SPEECHLESS|E|พูดไม่ออก
SPELLBOUND|E|หลงใหลจนตะลึง
ENCHANTED|E|มนต์เสน่ห์
CHARMED|E|ถูกมนต์สะกด
MESMERIZED|E|หลงใหลจนลืมตัว
CAPTIVATED|E|ถูกตรึงใจ
ENTHRALLED|E|หลงใหลอย่างมาก
OBSESSED|E|หมกมุ่น
FIXATED|E|ยึดติด
DISTRACTED|E|วอกแวก
PENSIVE|E|ครุ่นคิด
REFLECTIVE|E|ใคร่ครวญ
THOUGHTFUL|E|รอบคอบเอาใจใส่
MINDFUL|E|มีสติ
AWARE|E|ตระหนักรู้
OBLIVIOUS|E|ไม่รู้ตัว
IGNORANT|E|ไม่รู้เรื่อง
NAIVE|E|ไร้เดียงสา
INNOCENT|E|บริสุทธิ์ใจ
GULLIBLE|E|หลงเชื่อง่าย
SKEPTICAL|E|ขี้สงสัย
CYNICAL|E|มองโลกในแง่ร้าย
REALISTIC|E|สมจริง
IDEALISTIC|E|เพ้อฝันถึงอุดมคติ
PRACTICAL|E|ใช้ได้จริง
AMBITIOUS|E|ทะเยอทะยาน
DRIVEN|E|มีแรงผลักดัน
FOCUSED|E|มีสมาธิ
LAZY|E|ขี้เกียจ
SLUGGISH|E|เชื่องช้า
ENERGETIC|E|กระฉับกระเฉง
VIGOROUS|E|มีพลัง
LIVELY|E|มีชีวิตชีวา
DULL|E|น่าเบื่อ
MONOTONOUS|E|จำเจ
STIMULATED|E|ถูกกระตุ้น
AROUSED|E|ตื่นตัว
ALERT|E|ตื่นตัวระวังภัย
DROWSY|E|ง่วงเหงา
SLEEPY|E|ง่วงนอน
GROGGY|E|มึนงงจากการนอน
REFRESHED|E|สดชื่น
REVIVED|E|ฟื้นคืนพลัง
EXHAUSTED|E|หมดแรง
DRAINED|E|หมดพลังใจ
BURNOUT|E|หมดไฟในการทำงาน
OVERWORKED|E|ทำงานหนักเกินไป
VALUED|E|ได้รับคุณค่า
RESPECTED|E|ได้รับความเคารพ
ADMIRED|E|เป็นที่ชื่นชม
ESTEEMED|E|ได้รับการยกย่อง
HONORED|E|ได้รับเกียรติ
DIGNIFIED|E|มีศักดิ์ศรี
HUMBLE|E|ถ่อมตัว
MODEST|E|สุภาพเจียมตัว
ARROGANT|E|หยิ่งยโส
BOASTFUL|E|ชอบโอ้อวด
CONCEITED|E|หลงตัวเอง
VAIN|E|หยิ่งในรูปลักษณ์
SMUG|E|พอใจตัวเองเกินไป
HAUGHTY|E|เย่อหยิ่ง
RUDE|E|หยาบคาย
POLITE|E|สุภาพ
COURTEOUS|E|มีมารยาท
RESPECTFUL|E|ให้ความเคารพ
TACTLESS|E|ไม่มีไหวพริบ
BLUNT|E|พูดตรงไปตรงมา
DIPLOMATIC|E|มีชั้นเชิง
SINCERE|E|จริงใจ
GENUINE|E|แท้จริง
AUTHENTIC|E|เป็นตัวของตัวเอง
FAKE|E|ปลอม
HYPOCRITE|E|คนหน้าไหว้หลังหลอก
SUBMISSIVE|E|ยอมตาม
ASSERTIVE|E|กล้าแสดงออก
PASSIVE|E|เฉื่อยชา
AGGRESSIVE|E|ก้าวร้าว
DEFENSIVE|E|ตั้งรับ
RECEPTIVE|E|เปิดรับ
OPENMINDED|E|ใจกว้าง
TOLERANT|E|อดทนต่อความต่าง
PREJUDICE|E|อคติ
BIAS|E|ความลำเอียง
FAIRNESS|E|ความยุติธรรม
JUSTICE|E|ความยุติธรรม
EQUALITY|E|ความเท่าเทียม
EMPATHETIC|E|เข้าอกเข้าใจผู้อื่น
"""


def _parse():
    words = []
    seen = set()
    for line in _RAW.strip().splitlines():
        word, category, meaning = line.split("|", 2)
        word = word.strip().upper()
        if word in seen:
            continue
        seen.add(word)
        words.append((word, category.strip(), meaning.strip()))
    return words


WORDS = _parse()
