# Generated by Django 5.2.16 on 2026-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_internalplaceholder', 'Can view internal module')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
