# Generated by Django 4.2.30 on 2026-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('image', models.ImageField(upload_to='internal/icons/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
