# Generated by Django 4.2.30 on 2026-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_tag', models.CharField(help_text='e.g. DOC, HR, CERT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url_name', models.CharField(help_text="Django URL name, e.g. 'documents:list'", max_length=100)),
                ('icon_svg_path', models.TextField(blank=True, help_text='Inner <path>/<circle> markup for the module card icon (trusted, admin-authored).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True, help_text="False = 'coming soon' styling on the home page")),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_display_name', models.CharField(default='dTest.nexus', max_length=150)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'permissions': [],
            },
        ),
    ]
