# Generated by Django 4.2.30 on 2026-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('last_visited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
