# Generated by Django 4.2.30 on 2026-09-16 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageviewstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.SlugField(max_length=60)),
                ('page_label', models.CharField(max_length=120)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
