# Generated by Django 4.2.30 on 2026-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pageviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hero_bg_video',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
