# Generated by Django 4.2.30 on 2026-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_hero_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledefinition',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Home page menu strip background photo. Falls back to the line icon above if left blank.', null=True, upload_to='modules/'),
        ),
    ]
