# Generated by Django 5.2.16 on 2026-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moduledefinition_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('title_en', models.CharField(help_text='หัวข้อภาษาอังกฤษ (แสดงในเมนู About Us ด้วย)', max_length=60)),
                ('title_th', models.CharField(blank=True, help_text='ชื่อภาษาไทยที่แสดงเล็กๆ ข้างหัวข้อ', max_length=60)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
    ]
