# Generated by Django 5.2.16 on 2026-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_org_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tool_link_approve_doc',
            field=models.URLField(blank=True, help_text='Power Apps link for the Tools > Documents > Approve Doc tile.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tool_link_kace',
            field=models.URLField(blank=True, help_text='KACE Systems URL for the Tools > Systems tile.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tool_link_pscapa',
            field=models.URLField(blank=True, help_text='PScapa URL for the Tools > Systems tile.'),
        ),
    ]
