# Generated by Django 5.2.16 on 2026-09-23 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings_tool_link_approve_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledefinition',
            name='background_image_processed',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-regenerated from background_image + background_image_speed — never set directly.', null=True, upload_to='modules/processed/'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='background_image_speed',
            field=models.FloatField(default=1.0, help_text='Playback-speed multiplier applied when background_image is an animated GIF (>1 slows it down, <1 speeds it up, 1 = original speed). No effect on static images.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tool_link_approve_doc',
            field=models.URLField(blank=True, help_text='Power Apps link for the Tools > Systems > Approve Doc tile.'),
        ),
    ]
