# Generated by Django 5.2.16 on 2026-09-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_moduledefinition_background_image_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='แสดงในเมนู Standard และใช้เป็นข้อความแทนรูปโลโก้', max_length=80, verbose_name='ชื่อมาตรฐาน')),
                ('description', models.CharField(blank=True, help_text='ข้อความที่แสดงเมื่อเอาเมาส์ชี้โลโก้ (เว้นว่างได้)', max_length=200, verbose_name='คำอธิบาย')),
                ('logo', models.ImageField(upload_to='standards/', verbose_name='รูปโลโก้')),
                ('url', models.URLField(blank=True, help_text='เปิดในแท็บใหม่เมื่อกดโลโก้หรือเมนู — เว้นว่างได้ ถ้าไม่มีลิงก์ โลโก้จะกดไม่ได้', max_length=500, verbose_name='ลิงก์')),
                ('order', models.PositiveIntegerField(default=0, help_text='เลขน้อยแสดงก่อน', verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, help_text='ปิดเพื่อซ่อนชั่วคราวโดยไม่ต้องลบ', verbose_name='แสดงผล')),
            ],
            options={
                'verbose_name': 'มาตรฐาน (Standard)',
                'verbose_name_plural': 'มาตรฐาน (Standards)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
