# Generated by Django 4.2.30 on 2026-09-11 08:14

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_documentreport', 'Can view document reports'), ('export_documentreport', 'Can export document reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('local', 'Local'), ('google_drive', 'Google Drive'), ('sharepoint', 'SharePoint'), ('network_drive', 'Network Drive'), ('external_url', 'External URL')], default='local', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('business_unit', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.document_upload_path)),
                ('external_url', models.URLField(blank=True, help_text='Used when source is not Local (Drive/SharePoint/etc.)')),
                ('file_type', models.CharField(blank=True, help_text='File extension, e.g. pdf, xlsx, docx', max_length=20)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Size in bytes')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentsource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'permissions': [('download_document', 'Can download document'), ('upload_document', 'Can upload document')],
                'indexes': [models.Index(fields=['document_code'], name='documents_d_documen_88f2b5_idx'), models.Index(fields=['document_name'], name='documents_d_documen_d54dd2_idx'), models.Index(fields=['-updated_at'], name='documents_d_updated_98aa5e_idx'), models.Index(fields=['category', 'status'], name='documents_d_categor_0ec696_idx')],
            },
        ),
    ]
