# Generated by Django 4.2.30 on 2026-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Auto-detected from the code (e.g. SAM-25-... = 2025); editable when the code doesn't carry it.", null=True),
        ),
    ]
