# Generated by Django 4.2.30 on 2026-09-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indoor_unit',
            field=models.CharField(blank=True, help_text='Indoor unit model/name.', max_length=120),
        ),
        migrations.AddField(
            model_name='document',
            name='outdoor_unit',
            field=models.CharField(blank=True, help_text='Outdoor unit model/name.', max_length=120),
        ),
    ]
