# Generated by Django 4.2.30 on 2026-09-13 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_document_indoor_unit_document_outdoor_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='indoor_unit',
        ),
        migrations.RemoveField(
            model_name='document',
            name='outdoor_unit',
        ),
        migrations.CreateModel(
            name='EquipmentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('indoor_unit', models.CharField(help_text='Comma-separate multiple indoor models.', max_length=500)),
                ('outdoor_unit', models.CharField(blank=True, max_length=255)),
                ('report_dev_code', models.CharField(blank=True, help_text='Document code of the Dev report, if any.', max_length=60)),
                ('report_sam_code', models.CharField(blank=True, help_text='Document code of the Sam/Mass report, if any.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_specs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_specs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'id'],
            },
        ),
    ]
