# Generated by Django 5.2.16 on 2026-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilityplaceholder',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_utilityplaceholder', 'Can view tools module')]},
        ),
    ]
