# Generated by Django 5.2.16 on 2026-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_utilityplaceholder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('image', models.ImageField(upload_to='tools/icons/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
