# Generated by Django 4.2.30 on 2026-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_monitoringplaceholder', 'Can view monitoring module')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
